/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// AI content detection result
    /// </summary>
    [DataContract(Name = "AiContentDetectionResult")]
    public partial class AiContentDetectionResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiContentDetectionResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no AI-generated content was detected.</param>
        /// <param name="containsAiGeneratedContent">Content appears to be AI-generated.</param>
        /// <param name="aiConfidenceLevel">Confidence level of AI content detection (0.0 to 1.0).</param>
        /// <param name="skipped">Scan was skipped.</param>
        /// <param name="skipReason">Reason the scan was skipped.</param>
        /// <param name="verdict">Categorical assessment of whether the file appears AI-generated based on its  embedded metadata. One of: NoDeterministicAiMetadataFound, VerifiedAiGenerated,  VerifiedAiEditedOrComposite, LikelyAiGenerated, LikelyAiEditedOrComposite,  PossibleAiGenerated, ConflictingSignals, MetadataUnavailableOrUnreadable,  UnsupportedFileType..</param>
        /// <param name="provider">AI provider name (for example, \&quot;OpenAI\&quot;, \&quot;Adobe\&quot;, \&quot;Google\&quot;, \&quot;Microsoft\&quot;).  Empty when the metadata does not identify a provider..</param>
        /// <param name="generator">AI tool or product name (for example, \&quot;ChatGPT\&quot;, \&quot;Adobe Firefly\&quot;, \&quot;Stable  Diffusion\&quot;). Empty when the metadata does not identify a specific tool..</param>
        /// <param name="warnings">Non-fatal warnings produced during analysis, intended for diagnostic display.  Empty when no warnings were produced..</param>
        /// <param name="detectedFileType">File type detected from the file&#39;s content (for example, \&quot;jpeg\&quot;, \&quot;png\&quot;, \&quot;pdf\&quot;).  May differ from the file&#39;s name extension when the content was misnamed..</param>
        public AiContentDetectionResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), bool containsAiGeneratedContent = default(bool), double aiConfidenceLevel = default(double), bool skipped = default(bool), string skipReason = default(string), string verdict = default(string), string provider = default(string), string generator = default(string), List<string> warnings = default(List<string>), string detectedFileType = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.ContainsAiGeneratedContent = containsAiGeneratedContent;
            this.AiConfidenceLevel = aiConfidenceLevel;
            this.Skipped = skipped;
            this.SkipReason = skipReason;
            this.Verdict = verdict;
            this.Provider = provider;
            this.Generator = generator;
            this.Warnings = warnings;
            this.DetectedFileType = detectedFileType;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no AI-generated content was detected
        /// </summary>
        /// <value>True if no AI-generated content was detected</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Content appears to be AI-generated
        /// </summary>
        /// <value>Content appears to be AI-generated</value>
        [DataMember(Name = "ContainsAiGeneratedContent", EmitDefaultValue = true)]
        public bool ContainsAiGeneratedContent { get; set; }

        /// <summary>
        /// Confidence level of AI content detection (0.0 to 1.0)
        /// </summary>
        /// <value>Confidence level of AI content detection (0.0 to 1.0)</value>
        [DataMember(Name = "AiConfidenceLevel", EmitDefaultValue = false)]
        public double AiConfidenceLevel { get; set; }

        /// <summary>
        /// Scan was skipped
        /// </summary>
        /// <value>Scan was skipped</value>
        [DataMember(Name = "Skipped", EmitDefaultValue = true)]
        public bool Skipped { get; set; }

        /// <summary>
        /// Reason the scan was skipped
        /// </summary>
        /// <value>Reason the scan was skipped</value>
        [DataMember(Name = "SkipReason", EmitDefaultValue = false)]
        public string SkipReason { get; set; }

        /// <summary>
        /// Categorical assessment of whether the file appears AI-generated based on its  embedded metadata. One of: NoDeterministicAiMetadataFound, VerifiedAiGenerated,  VerifiedAiEditedOrComposite, LikelyAiGenerated, LikelyAiEditedOrComposite,  PossibleAiGenerated, ConflictingSignals, MetadataUnavailableOrUnreadable,  UnsupportedFileType.
        /// </summary>
        /// <value>Categorical assessment of whether the file appears AI-generated based on its  embedded metadata. One of: NoDeterministicAiMetadataFound, VerifiedAiGenerated,  VerifiedAiEditedOrComposite, LikelyAiGenerated, LikelyAiEditedOrComposite,  PossibleAiGenerated, ConflictingSignals, MetadataUnavailableOrUnreadable,  UnsupportedFileType.</value>
        [DataMember(Name = "Verdict", EmitDefaultValue = false)]
        public string Verdict { get; set; }

        /// <summary>
        /// AI provider name (for example, \&quot;OpenAI\&quot;, \&quot;Adobe\&quot;, \&quot;Google\&quot;, \&quot;Microsoft\&quot;).  Empty when the metadata does not identify a provider.
        /// </summary>
        /// <value>AI provider name (for example, \&quot;OpenAI\&quot;, \&quot;Adobe\&quot;, \&quot;Google\&quot;, \&quot;Microsoft\&quot;).  Empty when the metadata does not identify a provider.</value>
        [DataMember(Name = "Provider", EmitDefaultValue = false)]
        public string Provider { get; set; }

        /// <summary>
        /// AI tool or product name (for example, \&quot;ChatGPT\&quot;, \&quot;Adobe Firefly\&quot;, \&quot;Stable  Diffusion\&quot;). Empty when the metadata does not identify a specific tool.
        /// </summary>
        /// <value>AI tool or product name (for example, \&quot;ChatGPT\&quot;, \&quot;Adobe Firefly\&quot;, \&quot;Stable  Diffusion\&quot;). Empty when the metadata does not identify a specific tool.</value>
        [DataMember(Name = "Generator", EmitDefaultValue = false)]
        public string Generator { get; set; }

        /// <summary>
        /// Non-fatal warnings produced during analysis, intended for diagnostic display.  Empty when no warnings were produced.
        /// </summary>
        /// <value>Non-fatal warnings produced during analysis, intended for diagnostic display.  Empty when no warnings were produced.</value>
        [DataMember(Name = "Warnings", EmitDefaultValue = false)]
        public List<string> Warnings { get; set; }

        /// <summary>
        /// File type detected from the file&#39;s content (for example, \&quot;jpeg\&quot;, \&quot;png\&quot;, \&quot;pdf\&quot;).  May differ from the file&#39;s name extension when the content was misnamed.
        /// </summary>
        /// <value>File type detected from the file&#39;s content (for example, \&quot;jpeg\&quot;, \&quot;png\&quot;, \&quot;pdf\&quot;).  May differ from the file&#39;s name extension when the content was misnamed.</value>
        [DataMember(Name = "DetectedFileType", EmitDefaultValue = false)]
        public string DetectedFileType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiContentDetectionResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsAiGeneratedContent: ").Append(ContainsAiGeneratedContent).Append("\n");
            sb.Append("  AiConfidenceLevel: ").Append(AiConfidenceLevel).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  SkipReason: ").Append(SkipReason).Append("\n");
            sb.Append("  Verdict: ").Append(Verdict).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Generator: ").Append(Generator).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("  DetectedFileType: ").Append(DetectedFileType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
