/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// DLP (PII/PHI) detection configuration for text scanning
    /// </summary>
    [DataContract(Name = "DlpDetectionConfig")]
    public partial class DlpDetectionConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpDetectionConfig" /> class.
        /// </summary>
        /// <param name="enabled">Enable DLP detection.</param>
        /// <param name="allowEmailAddresses">Allow email addresses.</param>
        /// <param name="allowPhoneNumbers">Allow phone numbers.</param>
        /// <param name="allowStreetAddresses">Allow street addresses.</param>
        /// <param name="allowPersonNames">Allow person names.</param>
        /// <param name="allowBirthDates">Allow birth dates.</param>
        /// <param name="allowPassportNumbers">Allow passport numbers.</param>
        /// <param name="allowDriversLicenses">Allow driver&#39;s licenses.</param>
        /// <param name="allowSocialSecurityNumbers">Allow Social Security numbers.</param>
        /// <param name="allowTaxpayerIds">Allow taxpayer IDs.</param>
        /// <param name="allowCreditCardNumbers">Allow credit card numbers.</param>
        /// <param name="allowBankAccountNumbers">Allow bank account numbers.</param>
        /// <param name="allowIbans">Allow IBANs.</param>
        /// <param name="allowHealthInsuranceNumbers">Allow health insurance numbers.</param>
        /// <param name="allowBearerTokens">Allow bearer tokens.</param>
        /// <param name="allowHttpCookies">Allow HTTP cookies.</param>
        /// <param name="allowPrivateKeys">Allow private keys.</param>
        /// <param name="allowCredentials">Allow credentials.</param>
        /// <param name="allowDeepWebUrls">Allow deep web URLs.</param>
        /// <param name="allowSourceCode">Allow source code.</param>
        /// <param name="allowIpAddresses">Allow IP addresses.</param>
        /// <param name="allowMacAddresses">Allow MAC addresses.</param>
        /// <param name="allowHealthInsuranceMemberIds">Allow health insurance member IDs.</param>
        /// <param name="allowInjuryDiseaseReferences">Allow injury/disease references.</param>
        /// <param name="allowTreatmentTypeDescriptions">Allow treatment type descriptions.</param>
        /// <param name="allowMedicalTreatmentDates">Allow medical treatment dates.</param>
        /// <param name="allowHealthPlanBeneficiaryNumbers">Allow health plan beneficiary numbers.</param>
        /// <param name="allowTreatmentPayments">Allow treatment payments.</param>
        /// <param name="allowVehicleIds">Allow vehicle IDs.</param>
        /// <param name="allowDeviceIds">Allow device IDs.</param>
        /// <param name="provideAnalysisRationale">Provide analysis rationale.</param>
        /// <param name="customPolicyID">Custom policy ID.</param>
        public DlpDetectionConfig(bool enabled = default(bool), bool allowEmailAddresses = default(bool), bool allowPhoneNumbers = default(bool), bool allowStreetAddresses = default(bool), bool allowPersonNames = default(bool), bool allowBirthDates = default(bool), bool allowPassportNumbers = default(bool), bool allowDriversLicenses = default(bool), bool allowSocialSecurityNumbers = default(bool), bool allowTaxpayerIds = default(bool), bool allowCreditCardNumbers = default(bool), bool allowBankAccountNumbers = default(bool), bool allowIbans = default(bool), bool allowHealthInsuranceNumbers = default(bool), bool allowBearerTokens = default(bool), bool allowHttpCookies = default(bool), bool allowPrivateKeys = default(bool), bool allowCredentials = default(bool), bool allowDeepWebUrls = default(bool), bool allowSourceCode = default(bool), bool allowIpAddresses = default(bool), bool allowMacAddresses = default(bool), bool allowHealthInsuranceMemberIds = default(bool), bool allowInjuryDiseaseReferences = default(bool), bool allowTreatmentTypeDescriptions = default(bool), bool allowMedicalTreatmentDates = default(bool), bool allowHealthPlanBeneficiaryNumbers = default(bool), bool allowTreatmentPayments = default(bool), bool allowVehicleIds = default(bool), bool allowDeviceIds = default(bool), bool provideAnalysisRationale = default(bool), string customPolicyID = default(string))
        {
            this.Enabled = enabled;
            this.AllowEmailAddresses = allowEmailAddresses;
            this.AllowPhoneNumbers = allowPhoneNumbers;
            this.AllowStreetAddresses = allowStreetAddresses;
            this.AllowPersonNames = allowPersonNames;
            this.AllowBirthDates = allowBirthDates;
            this.AllowPassportNumbers = allowPassportNumbers;
            this.AllowDriversLicenses = allowDriversLicenses;
            this.AllowSocialSecurityNumbers = allowSocialSecurityNumbers;
            this.AllowTaxpayerIds = allowTaxpayerIds;
            this.AllowCreditCardNumbers = allowCreditCardNumbers;
            this.AllowBankAccountNumbers = allowBankAccountNumbers;
            this.AllowIbans = allowIbans;
            this.AllowHealthInsuranceNumbers = allowHealthInsuranceNumbers;
            this.AllowBearerTokens = allowBearerTokens;
            this.AllowHttpCookies = allowHttpCookies;
            this.AllowPrivateKeys = allowPrivateKeys;
            this.AllowCredentials = allowCredentials;
            this.AllowDeepWebUrls = allowDeepWebUrls;
            this.AllowSourceCode = allowSourceCode;
            this.AllowIpAddresses = allowIpAddresses;
            this.AllowMacAddresses = allowMacAddresses;
            this.AllowHealthInsuranceMemberIds = allowHealthInsuranceMemberIds;
            this.AllowInjuryDiseaseReferences = allowInjuryDiseaseReferences;
            this.AllowTreatmentTypeDescriptions = allowTreatmentTypeDescriptions;
            this.AllowMedicalTreatmentDates = allowMedicalTreatmentDates;
            this.AllowHealthPlanBeneficiaryNumbers = allowHealthPlanBeneficiaryNumbers;
            this.AllowTreatmentPayments = allowTreatmentPayments;
            this.AllowVehicleIds = allowVehicleIds;
            this.AllowDeviceIds = allowDeviceIds;
            this.ProvideAnalysisRationale = provideAnalysisRationale;
            this.CustomPolicyID = customPolicyID;
        }

        /// <summary>
        /// Enable DLP detection
        /// </summary>
        /// <value>Enable DLP detection</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Allow email addresses
        /// </summary>
        /// <value>Allow email addresses</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowEmailAddresses", EmitDefaultValue = true)]
        public bool AllowEmailAddresses { get; set; }

        /// <summary>
        /// Allow phone numbers
        /// </summary>
        /// <value>Allow phone numbers</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPhoneNumbers", EmitDefaultValue = true)]
        public bool AllowPhoneNumbers { get; set; }

        /// <summary>
        /// Allow street addresses
        /// </summary>
        /// <value>Allow street addresses</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowStreetAddresses", EmitDefaultValue = true)]
        public bool AllowStreetAddresses { get; set; }

        /// <summary>
        /// Allow person names
        /// </summary>
        /// <value>Allow person names</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPersonNames", EmitDefaultValue = true)]
        public bool AllowPersonNames { get; set; }

        /// <summary>
        /// Allow birth dates
        /// </summary>
        /// <value>Allow birth dates</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBirthDates", EmitDefaultValue = true)]
        public bool AllowBirthDates { get; set; }

        /// <summary>
        /// Allow passport numbers
        /// </summary>
        /// <value>Allow passport numbers</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPassportNumbers", EmitDefaultValue = true)]
        public bool AllowPassportNumbers { get; set; }

        /// <summary>
        /// Allow driver&#39;s licenses
        /// </summary>
        /// <value>Allow driver&#39;s licenses</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDriversLicenses", EmitDefaultValue = true)]
        public bool AllowDriversLicenses { get; set; }

        /// <summary>
        /// Allow Social Security numbers
        /// </summary>
        /// <value>Allow Social Security numbers</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowSocialSecurityNumbers", EmitDefaultValue = true)]
        public bool AllowSocialSecurityNumbers { get; set; }

        /// <summary>
        /// Allow taxpayer IDs
        /// </summary>
        /// <value>Allow taxpayer IDs</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowTaxpayerIds", EmitDefaultValue = true)]
        public bool AllowTaxpayerIds { get; set; }

        /// <summary>
        /// Allow credit card numbers
        /// </summary>
        /// <value>Allow credit card numbers</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCreditCardNumbers", EmitDefaultValue = true)]
        public bool AllowCreditCardNumbers { get; set; }

        /// <summary>
        /// Allow bank account numbers
        /// </summary>
        /// <value>Allow bank account numbers</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBankAccountNumbers", EmitDefaultValue = true)]
        public bool AllowBankAccountNumbers { get; set; }

        /// <summary>
        /// Allow IBANs
        /// </summary>
        /// <value>Allow IBANs</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowIbans", EmitDefaultValue = true)]
        public bool AllowIbans { get; set; }

        /// <summary>
        /// Allow health insurance numbers
        /// </summary>
        /// <value>Allow health insurance numbers</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthInsuranceNumbers", EmitDefaultValue = true)]
        public bool AllowHealthInsuranceNumbers { get; set; }

        /// <summary>
        /// Allow bearer tokens
        /// </summary>
        /// <value>Allow bearer tokens</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowBearerTokens", EmitDefaultValue = true)]
        public bool AllowBearerTokens { get; set; }

        /// <summary>
        /// Allow HTTP cookies
        /// </summary>
        /// <value>Allow HTTP cookies</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHttpCookies", EmitDefaultValue = true)]
        public bool AllowHttpCookies { get; set; }

        /// <summary>
        /// Allow private keys
        /// </summary>
        /// <value>Allow private keys</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPrivateKeys", EmitDefaultValue = true)]
        public bool AllowPrivateKeys { get; set; }

        /// <summary>
        /// Allow credentials
        /// </summary>
        /// <value>Allow credentials</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowCredentials", EmitDefaultValue = true)]
        public bool AllowCredentials { get; set; }

        /// <summary>
        /// Allow deep web URLs
        /// </summary>
        /// <value>Allow deep web URLs</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDeepWebUrls", EmitDefaultValue = true)]
        public bool AllowDeepWebUrls { get; set; }

        /// <summary>
        /// Allow source code
        /// </summary>
        /// <value>Allow source code</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowSourceCode", EmitDefaultValue = true)]
        public bool AllowSourceCode { get; set; }

        /// <summary>
        /// Allow IP addresses
        /// </summary>
        /// <value>Allow IP addresses</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowIpAddresses", EmitDefaultValue = true)]
        public bool AllowIpAddresses { get; set; }

        /// <summary>
        /// Allow MAC addresses
        /// </summary>
        /// <value>Allow MAC addresses</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowMacAddresses", EmitDefaultValue = true)]
        public bool AllowMacAddresses { get; set; }

        /// <summary>
        /// Allow health insurance member IDs
        /// </summary>
        /// <value>Allow health insurance member IDs</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthInsuranceMemberIds", EmitDefaultValue = true)]
        public bool AllowHealthInsuranceMemberIds { get; set; }

        /// <summary>
        /// Allow injury/disease references
        /// </summary>
        /// <value>Allow injury/disease references</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowInjuryDiseaseReferences", EmitDefaultValue = true)]
        public bool AllowInjuryDiseaseReferences { get; set; }

        /// <summary>
        /// Allow treatment type descriptions
        /// </summary>
        /// <value>Allow treatment type descriptions</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowTreatmentTypeDescriptions", EmitDefaultValue = true)]
        public bool AllowTreatmentTypeDescriptions { get; set; }

        /// <summary>
        /// Allow medical treatment dates
        /// </summary>
        /// <value>Allow medical treatment dates</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowMedicalTreatmentDates", EmitDefaultValue = true)]
        public bool AllowMedicalTreatmentDates { get; set; }

        /// <summary>
        /// Allow health plan beneficiary numbers
        /// </summary>
        /// <value>Allow health plan beneficiary numbers</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHealthPlanBeneficiaryNumbers", EmitDefaultValue = true)]
        public bool AllowHealthPlanBeneficiaryNumbers { get; set; }

        /// <summary>
        /// Allow treatment payments
        /// </summary>
        /// <value>Allow treatment payments</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowTreatmentPayments", EmitDefaultValue = true)]
        public bool AllowTreatmentPayments { get; set; }

        /// <summary>
        /// Allow vehicle IDs
        /// </summary>
        /// <value>Allow vehicle IDs</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowVehicleIds", EmitDefaultValue = true)]
        public bool AllowVehicleIds { get; set; }

        /// <summary>
        /// Allow device IDs
        /// </summary>
        /// <value>Allow device IDs</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowDeviceIds", EmitDefaultValue = true)]
        public bool AllowDeviceIds { get; set; }

        /// <summary>
        /// Provide analysis rationale
        /// </summary>
        /// <value>Provide analysis rationale</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "ProvideAnalysisRationale", EmitDefaultValue = true)]
        public bool ProvideAnalysisRationale { get; set; }

        /// <summary>
        /// Custom policy ID
        /// </summary>
        /// <value>Custom policy ID</value>
        [DataMember(Name = "CustomPolicyID", EmitDefaultValue = false)]
        public string CustomPolicyID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DlpDetectionConfig {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  AllowEmailAddresses: ").Append(AllowEmailAddresses).Append("\n");
            sb.Append("  AllowPhoneNumbers: ").Append(AllowPhoneNumbers).Append("\n");
            sb.Append("  AllowStreetAddresses: ").Append(AllowStreetAddresses).Append("\n");
            sb.Append("  AllowPersonNames: ").Append(AllowPersonNames).Append("\n");
            sb.Append("  AllowBirthDates: ").Append(AllowBirthDates).Append("\n");
            sb.Append("  AllowPassportNumbers: ").Append(AllowPassportNumbers).Append("\n");
            sb.Append("  AllowDriversLicenses: ").Append(AllowDriversLicenses).Append("\n");
            sb.Append("  AllowSocialSecurityNumbers: ").Append(AllowSocialSecurityNumbers).Append("\n");
            sb.Append("  AllowTaxpayerIds: ").Append(AllowTaxpayerIds).Append("\n");
            sb.Append("  AllowCreditCardNumbers: ").Append(AllowCreditCardNumbers).Append("\n");
            sb.Append("  AllowBankAccountNumbers: ").Append(AllowBankAccountNumbers).Append("\n");
            sb.Append("  AllowIbans: ").Append(AllowIbans).Append("\n");
            sb.Append("  AllowHealthInsuranceNumbers: ").Append(AllowHealthInsuranceNumbers).Append("\n");
            sb.Append("  AllowBearerTokens: ").Append(AllowBearerTokens).Append("\n");
            sb.Append("  AllowHttpCookies: ").Append(AllowHttpCookies).Append("\n");
            sb.Append("  AllowPrivateKeys: ").Append(AllowPrivateKeys).Append("\n");
            sb.Append("  AllowCredentials: ").Append(AllowCredentials).Append("\n");
            sb.Append("  AllowDeepWebUrls: ").Append(AllowDeepWebUrls).Append("\n");
            sb.Append("  AllowSourceCode: ").Append(AllowSourceCode).Append("\n");
            sb.Append("  AllowIpAddresses: ").Append(AllowIpAddresses).Append("\n");
            sb.Append("  AllowMacAddresses: ").Append(AllowMacAddresses).Append("\n");
            sb.Append("  AllowHealthInsuranceMemberIds: ").Append(AllowHealthInsuranceMemberIds).Append("\n");
            sb.Append("  AllowInjuryDiseaseReferences: ").Append(AllowInjuryDiseaseReferences).Append("\n");
            sb.Append("  AllowTreatmentTypeDescriptions: ").Append(AllowTreatmentTypeDescriptions).Append("\n");
            sb.Append("  AllowMedicalTreatmentDates: ").Append(AllowMedicalTreatmentDates).Append("\n");
            sb.Append("  AllowHealthPlanBeneficiaryNumbers: ").Append(AllowHealthPlanBeneficiaryNumbers).Append("\n");
            sb.Append("  AllowTreatmentPayments: ").Append(AllowTreatmentPayments).Append("\n");
            sb.Append("  AllowVehicleIds: ").Append(AllowVehicleIds).Append("\n");
            sb.Append("  AllowDeviceIds: ").Append(AllowDeviceIds).Append("\n");
            sb.Append("  ProvideAnalysisRationale: ").Append(ProvideAnalysisRationale).Append("\n");
            sb.Append("  CustomPolicyID: ").Append(CustomPolicyID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
