/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// DLP (PII/PHI) detection result
    /// </summary>
    [DataContract(Name = "DlpDetectionResult")]
    public partial class DlpDetectionResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DlpDetectionResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no PII/PHI was detected.</param>
        /// <param name="containsEmailAddresses">Contains email addresses.</param>
        /// <param name="containsPhoneNumbers">Contains phone numbers.</param>
        /// <param name="containsStreetAddresses">Contains street addresses.</param>
        /// <param name="containsPersonNames">Contains person names.</param>
        /// <param name="containsBirthDates">Contains birth dates.</param>
        /// <param name="containsPassportNumbers">Contains passport numbers.</param>
        /// <param name="containsDriversLicenses">Contains driver&#39;s licenses.</param>
        /// <param name="containsSocialSecurityNumbers">Contains Social Security numbers.</param>
        /// <param name="containsTaxpayerIds">Contains taxpayer IDs.</param>
        /// <param name="containsCreditCardNumbers">Contains credit card numbers.</param>
        /// <param name="containsBankAccountNumbers">Contains bank account numbers.</param>
        /// <param name="containsIbans">Contains IBANs.</param>
        /// <param name="containsHealthInsuranceNumbers">Contains health insurance numbers.</param>
        /// <param name="containsBearerTokens">Contains bearer tokens.</param>
        /// <param name="containsHttpCookies">Contains HTTP cookies.</param>
        /// <param name="containsPrivateKeys">Contains private keys.</param>
        /// <param name="containsCredentials">Contains credentials.</param>
        /// <param name="containsDeepWebUrls">Contains deep web URLs.</param>
        /// <param name="containsSourceCode">Contains source code.</param>
        /// <param name="containsIpAddresses">Contains IP addresses.</param>
        /// <param name="containsMacAddresses">Contains MAC addresses.</param>
        /// <param name="containsHealthInsuranceMemberIds">Contains health insurance member IDs.</param>
        /// <param name="containsInjuryDiseaseReferences">Contains injury/disease references.</param>
        /// <param name="containsTreatmentTypeDescriptions">Contains treatment type descriptions.</param>
        /// <param name="containsMedicalTreatmentDates">Contains medical treatment dates.</param>
        /// <param name="containsHealthPlanBeneficiaryNumbers">Contains health plan beneficiary numbers.</param>
        /// <param name="containsTreatmentPayments">Contains treatment payments.</param>
        /// <param name="containsVehicleIds">Contains vehicle IDs.</param>
        /// <param name="containsDeviceIds">Contains device IDs.</param>
        /// <param name="analysisRationale">Analysis rationale.</param>
        /// <param name="skipped">Scan was skipped.</param>
        /// <param name="skipReason">Reason the scan was skipped.</param>
        public DlpDetectionResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), bool containsEmailAddresses = default(bool), bool containsPhoneNumbers = default(bool), bool containsStreetAddresses = default(bool), bool containsPersonNames = default(bool), bool containsBirthDates = default(bool), bool containsPassportNumbers = default(bool), bool containsDriversLicenses = default(bool), bool containsSocialSecurityNumbers = default(bool), bool containsTaxpayerIds = default(bool), bool containsCreditCardNumbers = default(bool), bool containsBankAccountNumbers = default(bool), bool containsIbans = default(bool), bool containsHealthInsuranceNumbers = default(bool), bool containsBearerTokens = default(bool), bool containsHttpCookies = default(bool), bool containsPrivateKeys = default(bool), bool containsCredentials = default(bool), bool containsDeepWebUrls = default(bool), bool containsSourceCode = default(bool), bool containsIpAddresses = default(bool), bool containsMacAddresses = default(bool), bool containsHealthInsuranceMemberIds = default(bool), bool containsInjuryDiseaseReferences = default(bool), bool containsTreatmentTypeDescriptions = default(bool), bool containsMedicalTreatmentDates = default(bool), bool containsHealthPlanBeneficiaryNumbers = default(bool), bool containsTreatmentPayments = default(bool), bool containsVehicleIds = default(bool), bool containsDeviceIds = default(bool), string analysisRationale = default(string), bool skipped = default(bool), string skipReason = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.ContainsEmailAddresses = containsEmailAddresses;
            this.ContainsPhoneNumbers = containsPhoneNumbers;
            this.ContainsStreetAddresses = containsStreetAddresses;
            this.ContainsPersonNames = containsPersonNames;
            this.ContainsBirthDates = containsBirthDates;
            this.ContainsPassportNumbers = containsPassportNumbers;
            this.ContainsDriversLicenses = containsDriversLicenses;
            this.ContainsSocialSecurityNumbers = containsSocialSecurityNumbers;
            this.ContainsTaxpayerIds = containsTaxpayerIds;
            this.ContainsCreditCardNumbers = containsCreditCardNumbers;
            this.ContainsBankAccountNumbers = containsBankAccountNumbers;
            this.ContainsIbans = containsIbans;
            this.ContainsHealthInsuranceNumbers = containsHealthInsuranceNumbers;
            this.ContainsBearerTokens = containsBearerTokens;
            this.ContainsHttpCookies = containsHttpCookies;
            this.ContainsPrivateKeys = containsPrivateKeys;
            this.ContainsCredentials = containsCredentials;
            this.ContainsDeepWebUrls = containsDeepWebUrls;
            this.ContainsSourceCode = containsSourceCode;
            this.ContainsIpAddresses = containsIpAddresses;
            this.ContainsMacAddresses = containsMacAddresses;
            this.ContainsHealthInsuranceMemberIds = containsHealthInsuranceMemberIds;
            this.ContainsInjuryDiseaseReferences = containsInjuryDiseaseReferences;
            this.ContainsTreatmentTypeDescriptions = containsTreatmentTypeDescriptions;
            this.ContainsMedicalTreatmentDates = containsMedicalTreatmentDates;
            this.ContainsHealthPlanBeneficiaryNumbers = containsHealthPlanBeneficiaryNumbers;
            this.ContainsTreatmentPayments = containsTreatmentPayments;
            this.ContainsVehicleIds = containsVehicleIds;
            this.ContainsDeviceIds = containsDeviceIds;
            this.AnalysisRationale = analysisRationale;
            this.Skipped = skipped;
            this.SkipReason = skipReason;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no PII/PHI was detected
        /// </summary>
        /// <value>True if no PII/PHI was detected</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Contains email addresses
        /// </summary>
        /// <value>Contains email addresses</value>
        [DataMember(Name = "ContainsEmailAddresses", EmitDefaultValue = true)]
        public bool ContainsEmailAddresses { get; set; }

        /// <summary>
        /// Contains phone numbers
        /// </summary>
        /// <value>Contains phone numbers</value>
        [DataMember(Name = "ContainsPhoneNumbers", EmitDefaultValue = true)]
        public bool ContainsPhoneNumbers { get; set; }

        /// <summary>
        /// Contains street addresses
        /// </summary>
        /// <value>Contains street addresses</value>
        [DataMember(Name = "ContainsStreetAddresses", EmitDefaultValue = true)]
        public bool ContainsStreetAddresses { get; set; }

        /// <summary>
        /// Contains person names
        /// </summary>
        /// <value>Contains person names</value>
        [DataMember(Name = "ContainsPersonNames", EmitDefaultValue = true)]
        public bool ContainsPersonNames { get; set; }

        /// <summary>
        /// Contains birth dates
        /// </summary>
        /// <value>Contains birth dates</value>
        [DataMember(Name = "ContainsBirthDates", EmitDefaultValue = true)]
        public bool ContainsBirthDates { get; set; }

        /// <summary>
        /// Contains passport numbers
        /// </summary>
        /// <value>Contains passport numbers</value>
        [DataMember(Name = "ContainsPassportNumbers", EmitDefaultValue = true)]
        public bool ContainsPassportNumbers { get; set; }

        /// <summary>
        /// Contains driver&#39;s licenses
        /// </summary>
        /// <value>Contains driver&#39;s licenses</value>
        [DataMember(Name = "ContainsDriversLicenses", EmitDefaultValue = true)]
        public bool ContainsDriversLicenses { get; set; }

        /// <summary>
        /// Contains Social Security numbers
        /// </summary>
        /// <value>Contains Social Security numbers</value>
        [DataMember(Name = "ContainsSocialSecurityNumbers", EmitDefaultValue = true)]
        public bool ContainsSocialSecurityNumbers { get; set; }

        /// <summary>
        /// Contains taxpayer IDs
        /// </summary>
        /// <value>Contains taxpayer IDs</value>
        [DataMember(Name = "ContainsTaxpayerIds", EmitDefaultValue = true)]
        public bool ContainsTaxpayerIds { get; set; }

        /// <summary>
        /// Contains credit card numbers
        /// </summary>
        /// <value>Contains credit card numbers</value>
        [DataMember(Name = "ContainsCreditCardNumbers", EmitDefaultValue = true)]
        public bool ContainsCreditCardNumbers { get; set; }

        /// <summary>
        /// Contains bank account numbers
        /// </summary>
        /// <value>Contains bank account numbers</value>
        [DataMember(Name = "ContainsBankAccountNumbers", EmitDefaultValue = true)]
        public bool ContainsBankAccountNumbers { get; set; }

        /// <summary>
        /// Contains IBANs
        /// </summary>
        /// <value>Contains IBANs</value>
        [DataMember(Name = "ContainsIbans", EmitDefaultValue = true)]
        public bool ContainsIbans { get; set; }

        /// <summary>
        /// Contains health insurance numbers
        /// </summary>
        /// <value>Contains health insurance numbers</value>
        [DataMember(Name = "ContainsHealthInsuranceNumbers", EmitDefaultValue = true)]
        public bool ContainsHealthInsuranceNumbers { get; set; }

        /// <summary>
        /// Contains bearer tokens
        /// </summary>
        /// <value>Contains bearer tokens</value>
        [DataMember(Name = "ContainsBearerTokens", EmitDefaultValue = true)]
        public bool ContainsBearerTokens { get; set; }

        /// <summary>
        /// Contains HTTP cookies
        /// </summary>
        /// <value>Contains HTTP cookies</value>
        [DataMember(Name = "ContainsHttpCookies", EmitDefaultValue = true)]
        public bool ContainsHttpCookies { get; set; }

        /// <summary>
        /// Contains private keys
        /// </summary>
        /// <value>Contains private keys</value>
        [DataMember(Name = "ContainsPrivateKeys", EmitDefaultValue = true)]
        public bool ContainsPrivateKeys { get; set; }

        /// <summary>
        /// Contains credentials
        /// </summary>
        /// <value>Contains credentials</value>
        [DataMember(Name = "ContainsCredentials", EmitDefaultValue = true)]
        public bool ContainsCredentials { get; set; }

        /// <summary>
        /// Contains deep web URLs
        /// </summary>
        /// <value>Contains deep web URLs</value>
        [DataMember(Name = "ContainsDeepWebUrls", EmitDefaultValue = true)]
        public bool ContainsDeepWebUrls { get; set; }

        /// <summary>
        /// Contains source code
        /// </summary>
        /// <value>Contains source code</value>
        [DataMember(Name = "ContainsSourceCode", EmitDefaultValue = true)]
        public bool ContainsSourceCode { get; set; }

        /// <summary>
        /// Contains IP addresses
        /// </summary>
        /// <value>Contains IP addresses</value>
        [DataMember(Name = "ContainsIpAddresses", EmitDefaultValue = true)]
        public bool ContainsIpAddresses { get; set; }

        /// <summary>
        /// Contains MAC addresses
        /// </summary>
        /// <value>Contains MAC addresses</value>
        [DataMember(Name = "ContainsMacAddresses", EmitDefaultValue = true)]
        public bool ContainsMacAddresses { get; set; }

        /// <summary>
        /// Contains health insurance member IDs
        /// </summary>
        /// <value>Contains health insurance member IDs</value>
        [DataMember(Name = "ContainsHealthInsuranceMemberIds", EmitDefaultValue = true)]
        public bool ContainsHealthInsuranceMemberIds { get; set; }

        /// <summary>
        /// Contains injury/disease references
        /// </summary>
        /// <value>Contains injury/disease references</value>
        [DataMember(Name = "ContainsInjuryDiseaseReferences", EmitDefaultValue = true)]
        public bool ContainsInjuryDiseaseReferences { get; set; }

        /// <summary>
        /// Contains treatment type descriptions
        /// </summary>
        /// <value>Contains treatment type descriptions</value>
        [DataMember(Name = "ContainsTreatmentTypeDescriptions", EmitDefaultValue = true)]
        public bool ContainsTreatmentTypeDescriptions { get; set; }

        /// <summary>
        /// Contains medical treatment dates
        /// </summary>
        /// <value>Contains medical treatment dates</value>
        [DataMember(Name = "ContainsMedicalTreatmentDates", EmitDefaultValue = true)]
        public bool ContainsMedicalTreatmentDates { get; set; }

        /// <summary>
        /// Contains health plan beneficiary numbers
        /// </summary>
        /// <value>Contains health plan beneficiary numbers</value>
        [DataMember(Name = "ContainsHealthPlanBeneficiaryNumbers", EmitDefaultValue = true)]
        public bool ContainsHealthPlanBeneficiaryNumbers { get; set; }

        /// <summary>
        /// Contains treatment payments
        /// </summary>
        /// <value>Contains treatment payments</value>
        [DataMember(Name = "ContainsTreatmentPayments", EmitDefaultValue = true)]
        public bool ContainsTreatmentPayments { get; set; }

        /// <summary>
        /// Contains vehicle IDs
        /// </summary>
        /// <value>Contains vehicle IDs</value>
        [DataMember(Name = "ContainsVehicleIds", EmitDefaultValue = true)]
        public bool ContainsVehicleIds { get; set; }

        /// <summary>
        /// Contains device IDs
        /// </summary>
        /// <value>Contains device IDs</value>
        [DataMember(Name = "ContainsDeviceIds", EmitDefaultValue = true)]
        public bool ContainsDeviceIds { get; set; }

        /// <summary>
        /// Analysis rationale
        /// </summary>
        /// <value>Analysis rationale</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Scan was skipped
        /// </summary>
        /// <value>Scan was skipped</value>
        [DataMember(Name = "Skipped", EmitDefaultValue = true)]
        public bool Skipped { get; set; }

        /// <summary>
        /// Reason the scan was skipped
        /// </summary>
        /// <value>Reason the scan was skipped</value>
        [DataMember(Name = "SkipReason", EmitDefaultValue = false)]
        public string SkipReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DlpDetectionResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsEmailAddresses: ").Append(ContainsEmailAddresses).Append("\n");
            sb.Append("  ContainsPhoneNumbers: ").Append(ContainsPhoneNumbers).Append("\n");
            sb.Append("  ContainsStreetAddresses: ").Append(ContainsStreetAddresses).Append("\n");
            sb.Append("  ContainsPersonNames: ").Append(ContainsPersonNames).Append("\n");
            sb.Append("  ContainsBirthDates: ").Append(ContainsBirthDates).Append("\n");
            sb.Append("  ContainsPassportNumbers: ").Append(ContainsPassportNumbers).Append("\n");
            sb.Append("  ContainsDriversLicenses: ").Append(ContainsDriversLicenses).Append("\n");
            sb.Append("  ContainsSocialSecurityNumbers: ").Append(ContainsSocialSecurityNumbers).Append("\n");
            sb.Append("  ContainsTaxpayerIds: ").Append(ContainsTaxpayerIds).Append("\n");
            sb.Append("  ContainsCreditCardNumbers: ").Append(ContainsCreditCardNumbers).Append("\n");
            sb.Append("  ContainsBankAccountNumbers: ").Append(ContainsBankAccountNumbers).Append("\n");
            sb.Append("  ContainsIbans: ").Append(ContainsIbans).Append("\n");
            sb.Append("  ContainsHealthInsuranceNumbers: ").Append(ContainsHealthInsuranceNumbers).Append("\n");
            sb.Append("  ContainsBearerTokens: ").Append(ContainsBearerTokens).Append("\n");
            sb.Append("  ContainsHttpCookies: ").Append(ContainsHttpCookies).Append("\n");
            sb.Append("  ContainsPrivateKeys: ").Append(ContainsPrivateKeys).Append("\n");
            sb.Append("  ContainsCredentials: ").Append(ContainsCredentials).Append("\n");
            sb.Append("  ContainsDeepWebUrls: ").Append(ContainsDeepWebUrls).Append("\n");
            sb.Append("  ContainsSourceCode: ").Append(ContainsSourceCode).Append("\n");
            sb.Append("  ContainsIpAddresses: ").Append(ContainsIpAddresses).Append("\n");
            sb.Append("  ContainsMacAddresses: ").Append(ContainsMacAddresses).Append("\n");
            sb.Append("  ContainsHealthInsuranceMemberIds: ").Append(ContainsHealthInsuranceMemberIds).Append("\n");
            sb.Append("  ContainsInjuryDiseaseReferences: ").Append(ContainsInjuryDiseaseReferences).Append("\n");
            sb.Append("  ContainsTreatmentTypeDescriptions: ").Append(ContainsTreatmentTypeDescriptions).Append("\n");
            sb.Append("  ContainsMedicalTreatmentDates: ").Append(ContainsMedicalTreatmentDates).Append("\n");
            sb.Append("  ContainsHealthPlanBeneficiaryNumbers: ").Append(ContainsHealthPlanBeneficiaryNumbers).Append("\n");
            sb.Append("  ContainsTreatmentPayments: ").Append(ContainsTreatmentPayments).Append("\n");
            sb.Append("  ContainsVehicleIds: ").Append(ContainsVehicleIds).Append("\n");
            sb.Append("  ContainsDeviceIds: ").Append(ContainsDeviceIds).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  SkipReason: ").Append(SkipReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
