/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Fraud detection result
    /// </summary>
    [DataContract(Name = "FraudDetectionResult")]
    public partial class FraudDetectionResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FraudDetectionResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no fraud was detected.</param>
        /// <param name="fraudRiskLevel">Fraud risk level (0.0 to 1.0).</param>
        /// <param name="containsFinancialLiability">Document contains financial liability language.</param>
        /// <param name="containsSensitiveInformationCollection">Document collects sensitive information.</param>
        /// <param name="containsAssetTransfer">Document involves asset transfer.</param>
        /// <param name="containsPurchaseAgreement">Document is a purchase agreement.</param>
        /// <param name="containsEmploymentAgreement">Document is an employment agreement.</param>
        /// <param name="containsExpiredDocument">Document is expired.</param>
        /// <param name="containsAiGeneratedContent">Document contains AI-generated content.</param>
        /// <param name="analysisRationale">Analysis rationale.</param>
        /// <param name="documentClass">Document class/type.</param>
        /// <param name="skipped">Scan was skipped.</param>
        /// <param name="skipReason">Reason the scan was skipped.</param>
        public FraudDetectionResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), double fraudRiskLevel = default(double), bool containsFinancialLiability = default(bool), bool containsSensitiveInformationCollection = default(bool), bool containsAssetTransfer = default(bool), bool containsPurchaseAgreement = default(bool), bool containsEmploymentAgreement = default(bool), bool containsExpiredDocument = default(bool), bool containsAiGeneratedContent = default(bool), string analysisRationale = default(string), string documentClass = default(string), bool skipped = default(bool), string skipReason = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.FraudRiskLevel = fraudRiskLevel;
            this.ContainsFinancialLiability = containsFinancialLiability;
            this.ContainsSensitiveInformationCollection = containsSensitiveInformationCollection;
            this.ContainsAssetTransfer = containsAssetTransfer;
            this.ContainsPurchaseAgreement = containsPurchaseAgreement;
            this.ContainsEmploymentAgreement = containsEmploymentAgreement;
            this.ContainsExpiredDocument = containsExpiredDocument;
            this.ContainsAiGeneratedContent = containsAiGeneratedContent;
            this.AnalysisRationale = analysisRationale;
            this.DocumentClass = documentClass;
            this.Skipped = skipped;
            this.SkipReason = skipReason;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no fraud was detected
        /// </summary>
        /// <value>True if no fraud was detected</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Fraud risk level (0.0 to 1.0)
        /// </summary>
        /// <value>Fraud risk level (0.0 to 1.0)</value>
        [DataMember(Name = "FraudRiskLevel", EmitDefaultValue = false)]
        public double FraudRiskLevel { get; set; }

        /// <summary>
        /// Document contains financial liability language
        /// </summary>
        /// <value>Document contains financial liability language</value>
        [DataMember(Name = "ContainsFinancialLiability", EmitDefaultValue = true)]
        public bool ContainsFinancialLiability { get; set; }

        /// <summary>
        /// Document collects sensitive information
        /// </summary>
        /// <value>Document collects sensitive information</value>
        [DataMember(Name = "ContainsSensitiveInformationCollection", EmitDefaultValue = true)]
        public bool ContainsSensitiveInformationCollection { get; set; }

        /// <summary>
        /// Document involves asset transfer
        /// </summary>
        /// <value>Document involves asset transfer</value>
        [DataMember(Name = "ContainsAssetTransfer", EmitDefaultValue = true)]
        public bool ContainsAssetTransfer { get; set; }

        /// <summary>
        /// Document is a purchase agreement
        /// </summary>
        /// <value>Document is a purchase agreement</value>
        [DataMember(Name = "ContainsPurchaseAgreement", EmitDefaultValue = true)]
        public bool ContainsPurchaseAgreement { get; set; }

        /// <summary>
        /// Document is an employment agreement
        /// </summary>
        /// <value>Document is an employment agreement</value>
        [DataMember(Name = "ContainsEmploymentAgreement", EmitDefaultValue = true)]
        public bool ContainsEmploymentAgreement { get; set; }

        /// <summary>
        /// Document is expired
        /// </summary>
        /// <value>Document is expired</value>
        [DataMember(Name = "ContainsExpiredDocument", EmitDefaultValue = true)]
        public bool ContainsExpiredDocument { get; set; }

        /// <summary>
        /// Document contains AI-generated content
        /// </summary>
        /// <value>Document contains AI-generated content</value>
        [DataMember(Name = "ContainsAiGeneratedContent", EmitDefaultValue = true)]
        public bool ContainsAiGeneratedContent { get; set; }

        /// <summary>
        /// Analysis rationale
        /// </summary>
        /// <value>Analysis rationale</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Document class/type
        /// </summary>
        /// <value>Document class/type</value>
        [DataMember(Name = "DocumentClass", EmitDefaultValue = false)]
        public string DocumentClass { get; set; }

        /// <summary>
        /// Scan was skipped
        /// </summary>
        /// <value>Scan was skipped</value>
        [DataMember(Name = "Skipped", EmitDefaultValue = true)]
        public bool Skipped { get; set; }

        /// <summary>
        /// Reason the scan was skipped
        /// </summary>
        /// <value>Reason the scan was skipped</value>
        [DataMember(Name = "SkipReason", EmitDefaultValue = false)]
        public string SkipReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FraudDetectionResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  FraudRiskLevel: ").Append(FraudRiskLevel).Append("\n");
            sb.Append("  ContainsFinancialLiability: ").Append(ContainsFinancialLiability).Append("\n");
            sb.Append("  ContainsSensitiveInformationCollection: ").Append(ContainsSensitiveInformationCollection).Append("\n");
            sb.Append("  ContainsAssetTransfer: ").Append(ContainsAssetTransfer).Append("\n");
            sb.Append("  ContainsPurchaseAgreement: ").Append(ContainsPurchaseAgreement).Append("\n");
            sb.Append("  ContainsEmploymentAgreement: ").Append(ContainsEmploymentAgreement).Append("\n");
            sb.Append("  ContainsExpiredDocument: ").Append(ContainsExpiredDocument).Append("\n");
            sb.Append("  ContainsAiGeneratedContent: ").Append(ContainsAiGeneratedContent).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("  DocumentClass: ").Append(DocumentClass).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  SkipReason: ").Append(SkipReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
