/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Fraud detection configuration
    /// </summary>
    [DataContract(Name = "FraudDetectionConfig")]
    public partial class FraudDetectionConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FraudDetectionConfig" /> class.
        /// </summary>
        /// <param name="enabled">Enable fraud detection.</param>
        /// <param name="preprocessing">Preprocessing mode: Auto or None.</param>
        /// <param name="resultCrossCheck">Result cross-check mode: None or Advanced.</param>
        /// <param name="userEmailAddress">User email address for verification context.</param>
        /// <param name="userEmailAddressVerified">Whether the user email has been verified.</param>
        public FraudDetectionConfig(bool enabled = default(bool), string preprocessing = default(string), string resultCrossCheck = default(string), string userEmailAddress = default(string), bool userEmailAddressVerified = default(bool))
        {
            this.Enabled = enabled;
            this.Preprocessing = preprocessing;
            this.ResultCrossCheck = resultCrossCheck;
            this.UserEmailAddress = userEmailAddress;
            this.UserEmailAddressVerified = userEmailAddressVerified;
        }

        /// <summary>
        /// Enable fraud detection
        /// </summary>
        /// <value>Enable fraud detection</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Preprocessing mode: Auto or None
        /// </summary>
        /// <value>Preprocessing mode: Auto or None</value>
        /*
        <example>Auto</example>
        */
        [DataMember(Name = "Preprocessing", EmitDefaultValue = false)]
        public string Preprocessing { get; set; }

        /// <summary>
        /// Result cross-check mode: None or Advanced
        /// </summary>
        /// <value>Result cross-check mode: None or Advanced</value>
        /*
        <example>None</example>
        */
        [DataMember(Name = "ResultCrossCheck", EmitDefaultValue = false)]
        public string ResultCrossCheck { get; set; }

        /// <summary>
        /// User email address for verification context
        /// </summary>
        /// <value>User email address for verification context</value>
        [DataMember(Name = "UserEmailAddress", EmitDefaultValue = false)]
        public string UserEmailAddress { get; set; }

        /// <summary>
        /// Whether the user email has been verified
        /// </summary>
        /// <value>Whether the user email has been verified</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "UserEmailAddressVerified", EmitDefaultValue = true)]
        public bool UserEmailAddressVerified { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FraudDetectionConfig {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Preprocessing: ").Append(Preprocessing).Append("\n");
            sb.Append("  ResultCrossCheck: ").Append(ResultCrossCheck).Append("\n");
            sb.Append("  UserEmailAddress: ").Append(UserEmailAddress).Append("\n");
            sb.Append("  UserEmailAddressVerified: ").Append(UserEmailAddressVerified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
