/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Request to scan text for multiple threat types
    /// </summary>
    [DataContract(Name = "MultiThreatTextRequest")]
    public partial class MultiThreatTextRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiThreatTextRequest" /> class.
        /// </summary>
        /// <param name="textContent">The text content to scan.</param>
        /// <param name="virusScan">virusScan.</param>
        /// <param name="phishingDetection">phishingDetection.</param>
        /// <param name="spamDetection">spamDetection.</param>
        /// <param name="dlpDetection">dlpDetection.</param>
        /// <param name="policyEnforcement">policyEnforcement.</param>
        public MultiThreatTextRequest(string textContent = default(string), VirusScanConfig virusScan = default(VirusScanConfig), PhishingDetectionTextConfig phishingDetection = default(PhishingDetectionTextConfig), SpamDetectionConfig spamDetection = default(SpamDetectionConfig), DlpDetectionConfig dlpDetection = default(DlpDetectionConfig), PolicyEnforcementConfig policyEnforcement = default(PolicyEnforcementConfig))
        {
            this.TextContent = textContent;
            this.VirusScan = virusScan;
            this.PhishingDetection = phishingDetection;
            this.SpamDetection = spamDetection;
            this.DlpDetection = dlpDetection;
            this.PolicyEnforcement = policyEnforcement;
        }

        /// <summary>
        /// The text content to scan
        /// </summary>
        /// <value>The text content to scan</value>
        /*
        <example>Check out this amazing offer at http://example.com</example>
        */
        [DataMember(Name = "TextContent", EmitDefaultValue = false)]
        public string TextContent { get; set; }

        /// <summary>
        /// Gets or Sets VirusScan
        /// </summary>
        [DataMember(Name = "VirusScan", EmitDefaultValue = false)]
        public VirusScanConfig VirusScan { get; set; }

        /// <summary>
        /// Gets or Sets PhishingDetection
        /// </summary>
        [DataMember(Name = "PhishingDetection", EmitDefaultValue = false)]
        public PhishingDetectionTextConfig PhishingDetection { get; set; }

        /// <summary>
        /// Gets or Sets SpamDetection
        /// </summary>
        [DataMember(Name = "SpamDetection", EmitDefaultValue = false)]
        public SpamDetectionConfig SpamDetection { get; set; }

        /// <summary>
        /// Gets or Sets DlpDetection
        /// </summary>
        [DataMember(Name = "DlpDetection", EmitDefaultValue = false)]
        public DlpDetectionConfig DlpDetection { get; set; }

        /// <summary>
        /// Gets or Sets PolicyEnforcement
        /// </summary>
        [DataMember(Name = "PolicyEnforcement", EmitDefaultValue = false)]
        public PolicyEnforcementConfig PolicyEnforcement { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MultiThreatTextRequest {\n");
            sb.Append("  TextContent: ").Append(TextContent).Append("\n");
            sb.Append("  VirusScan: ").Append(VirusScan).Append("\n");
            sb.Append("  PhishingDetection: ").Append(PhishingDetection).Append("\n");
            sb.Append("  SpamDetection: ").Append(SpamDetection).Append("\n");
            sb.Append("  DlpDetection: ").Append(DlpDetection).Append("\n");
            sb.Append("  PolicyEnforcement: ").Append(PolicyEnforcement).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
