/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Response from a multi-threat URL scan
    /// </summary>
    [DataContract(Name = "MultiThreatUrlResponse")]
    public partial class MultiThreatUrlResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiThreatUrlResponse" /> class.
        /// </summary>
        /// <param name="successful">True if the scan completed successfully.</param>
        /// <param name="cleanResult">True if all enabled scans returned clean results.</param>
        /// <param name="scanResults">scanResults.</param>
        public MultiThreatUrlResponse(bool successful = default(bool), bool cleanResult = default(bool), UrlScanResults scanResults = default(UrlScanResults))
        {
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.ScanResults = scanResults;
        }

        /// <summary>
        /// True if the scan completed successfully
        /// </summary>
        /// <value>True if the scan completed successfully</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if all enabled scans returned clean results
        /// </summary>
        /// <value>True if all enabled scans returned clean results</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Gets or Sets ScanResults
        /// </summary>
        [DataMember(Name = "ScanResults", EmitDefaultValue = false)]
        public UrlScanResults ScanResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MultiThreatUrlResponse {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ScanResults: ").Append(ScanResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
