/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Request to scan a URL for multiple threat types
    /// </summary>
    [DataContract(Name = "MultiThreatUrlRequest")]
    public partial class MultiThreatUrlRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiThreatUrlRequest" /> class.
        /// </summary>
        /// <param name="url">The URL to scan (must include http:// or https://).</param>
        /// <param name="virusScan">virusScan.</param>
        /// <param name="phishingDetection">phishingDetection.</param>
        /// <param name="policyEnforcement">policyEnforcement.</param>
        /// <param name="contentScanning">contentScanning.</param>
        public MultiThreatUrlRequest(string url = default(string), UrlVirusScanConfig virusScan = default(UrlVirusScanConfig), UrlPhishingDetectionConfig phishingDetection = default(UrlPhishingDetectionConfig), PolicyEnforcementConfig policyEnforcement = default(PolicyEnforcementConfig), ContentScanningConfig contentScanning = default(ContentScanningConfig))
        {
            this.Url = url;
            this.VirusScan = virusScan;
            this.PhishingDetection = phishingDetection;
            this.PolicyEnforcement = policyEnforcement;
            this.ContentScanning = contentScanning;
        }

        /// <summary>
        /// The URL to scan (must include http:// or https://)
        /// </summary>
        /// <value>The URL to scan (must include http:// or https://)</value>
        /*
        <example>https://example.com</example>
        */
        [DataMember(Name = "Url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets VirusScan
        /// </summary>
        [DataMember(Name = "VirusScan", EmitDefaultValue = false)]
        public UrlVirusScanConfig VirusScan { get; set; }

        /// <summary>
        /// Gets or Sets PhishingDetection
        /// </summary>
        [DataMember(Name = "PhishingDetection", EmitDefaultValue = false)]
        public UrlPhishingDetectionConfig PhishingDetection { get; set; }

        /// <summary>
        /// Gets or Sets PolicyEnforcement
        /// </summary>
        [DataMember(Name = "PolicyEnforcement", EmitDefaultValue = false)]
        public PolicyEnforcementConfig PolicyEnforcement { get; set; }

        /// <summary>
        /// Gets or Sets ContentScanning
        /// </summary>
        [DataMember(Name = "ContentScanning", EmitDefaultValue = false)]
        public ContentScanningConfig ContentScanning { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MultiThreatUrlRequest {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  VirusScan: ").Append(VirusScan).Append("\n");
            sb.Append("  PhishingDetection: ").Append(PhishingDetection).Append("\n");
            sb.Append("  PolicyEnforcement: ").Append(PolicyEnforcement).Append("\n");
            sb.Append("  ContentScanning: ").Append(ContentScanning).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
