/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// NSFW detection result
    /// </summary>
    [DataContract(Name = "NsfwDetectionResult")]
    public partial class NsfwDetectionResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NsfwDetectionResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no NSFW content was found.</param>
        /// <param name="containsNudity">Image contains nudity.</param>
        /// <param name="containsGraphicViolence">Image contains graphic violence.</param>
        /// <param name="containsNonGraphicViolence">Image contains non-graphic violence.</param>
        /// <param name="containsSelfHarm">Image contains self-harm content.</param>
        /// <param name="containsHate">Image contains hate content.</param>
        /// <param name="containsPotentialIllegalActivity">Image contains potential illegal activity.</param>
        /// <param name="containsMedicalImagery">Image contains medical imagery.</param>
        /// <param name="containsProfanity">Image contains profanity.</param>
        /// <param name="score">NSFW score (0.0 to 1.0).</param>
        /// <param name="classificationOutcome">Classification outcome.</param>
        /// <param name="skipped">Scan was skipped (unsupported format).</param>
        /// <param name="skipReason">Reason the scan was skipped.</param>
        public NsfwDetectionResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), bool containsNudity = default(bool), bool containsGraphicViolence = default(bool), bool containsNonGraphicViolence = default(bool), bool containsSelfHarm = default(bool), bool containsHate = default(bool), bool containsPotentialIllegalActivity = default(bool), bool containsMedicalImagery = default(bool), bool containsProfanity = default(bool), double score = default(double), string classificationOutcome = default(string), bool skipped = default(bool), string skipReason = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.ContainsNudity = containsNudity;
            this.ContainsGraphicViolence = containsGraphicViolence;
            this.ContainsNonGraphicViolence = containsNonGraphicViolence;
            this.ContainsSelfHarm = containsSelfHarm;
            this.ContainsHate = containsHate;
            this.ContainsPotentialIllegalActivity = containsPotentialIllegalActivity;
            this.ContainsMedicalImagery = containsMedicalImagery;
            this.ContainsProfanity = containsProfanity;
            this.Score = score;
            this.ClassificationOutcome = classificationOutcome;
            this.Skipped = skipped;
            this.SkipReason = skipReason;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no NSFW content was found
        /// </summary>
        /// <value>True if no NSFW content was found</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Image contains nudity
        /// </summary>
        /// <value>Image contains nudity</value>
        [DataMember(Name = "ContainsNudity", EmitDefaultValue = true)]
        public bool ContainsNudity { get; set; }

        /// <summary>
        /// Image contains graphic violence
        /// </summary>
        /// <value>Image contains graphic violence</value>
        [DataMember(Name = "ContainsGraphicViolence", EmitDefaultValue = true)]
        public bool ContainsGraphicViolence { get; set; }

        /// <summary>
        /// Image contains non-graphic violence
        /// </summary>
        /// <value>Image contains non-graphic violence</value>
        [DataMember(Name = "ContainsNonGraphicViolence", EmitDefaultValue = true)]
        public bool ContainsNonGraphicViolence { get; set; }

        /// <summary>
        /// Image contains self-harm content
        /// </summary>
        /// <value>Image contains self-harm content</value>
        [DataMember(Name = "ContainsSelfHarm", EmitDefaultValue = true)]
        public bool ContainsSelfHarm { get; set; }

        /// <summary>
        /// Image contains hate content
        /// </summary>
        /// <value>Image contains hate content</value>
        [DataMember(Name = "ContainsHate", EmitDefaultValue = true)]
        public bool ContainsHate { get; set; }

        /// <summary>
        /// Image contains potential illegal activity
        /// </summary>
        /// <value>Image contains potential illegal activity</value>
        [DataMember(Name = "ContainsPotentialIllegalActivity", EmitDefaultValue = true)]
        public bool ContainsPotentialIllegalActivity { get; set; }

        /// <summary>
        /// Image contains medical imagery
        /// </summary>
        /// <value>Image contains medical imagery</value>
        [DataMember(Name = "ContainsMedicalImagery", EmitDefaultValue = true)]
        public bool ContainsMedicalImagery { get; set; }

        /// <summary>
        /// Image contains profanity
        /// </summary>
        /// <value>Image contains profanity</value>
        [DataMember(Name = "ContainsProfanity", EmitDefaultValue = true)]
        public bool ContainsProfanity { get; set; }

        /// <summary>
        /// NSFW score (0.0 to 1.0)
        /// </summary>
        /// <value>NSFW score (0.0 to 1.0)</value>
        [DataMember(Name = "Score", EmitDefaultValue = false)]
        public double Score { get; set; }

        /// <summary>
        /// Classification outcome
        /// </summary>
        /// <value>Classification outcome</value>
        [DataMember(Name = "ClassificationOutcome", EmitDefaultValue = false)]
        public string ClassificationOutcome { get; set; }

        /// <summary>
        /// Scan was skipped (unsupported format)
        /// </summary>
        /// <value>Scan was skipped (unsupported format)</value>
        [DataMember(Name = "Skipped", EmitDefaultValue = true)]
        public bool Skipped { get; set; }

        /// <summary>
        /// Reason the scan was skipped
        /// </summary>
        /// <value>Reason the scan was skipped</value>
        [DataMember(Name = "SkipReason", EmitDefaultValue = false)]
        public string SkipReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NsfwDetectionResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsNudity: ").Append(ContainsNudity).Append("\n");
            sb.Append("  ContainsGraphicViolence: ").Append(ContainsGraphicViolence).Append("\n");
            sb.Append("  ContainsNonGraphicViolence: ").Append(ContainsNonGraphicViolence).Append("\n");
            sb.Append("  ContainsSelfHarm: ").Append(ContainsSelfHarm).Append("\n");
            sb.Append("  ContainsHate: ").Append(ContainsHate).Append("\n");
            sb.Append("  ContainsPotentialIllegalActivity: ").Append(ContainsPotentialIllegalActivity).Append("\n");
            sb.Append("  ContainsMedicalImagery: ").Append(ContainsMedicalImagery).Append("\n");
            sb.Append("  ContainsProfanity: ").Append(ContainsProfanity).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  ClassificationOutcome: ").Append(ClassificationOutcome).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  SkipReason: ").Append(SkipReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
