/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Phishing detection result for URL scanning
    /// </summary>
    [DataContract(Name = "PhishingDetectionUrlResult")]
    public partial class PhishingDetectionUrlResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionUrlResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no phishing was detected.</param>
        /// <param name="phishingRiskLevel">Phishing risk level (0.0 to 1.0).</param>
        /// <param name="isSsrfThreat">URL is a server-side request forgery threat.</param>
        /// <param name="containsPhishing">URL contains phishing.</param>
        /// <param name="containsUnsolicitedSales">URL contains unsolicited sales.</param>
        /// <param name="containsPromotionalContent">URL contains promotional content.</param>
        /// <param name="containsPhishingAttempt">URL contains phishing attempt.</param>
        /// <param name="analysisRationale">Analysis rationale.</param>
        public PhishingDetectionUrlResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), double phishingRiskLevel = default(double), bool isSsrfThreat = default(bool), bool containsPhishing = default(bool), bool containsUnsolicitedSales = default(bool), bool containsPromotionalContent = default(bool), bool containsPhishingAttempt = default(bool), string analysisRationale = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.PhishingRiskLevel = phishingRiskLevel;
            this.IsSsrfThreat = isSsrfThreat;
            this.ContainsPhishing = containsPhishing;
            this.ContainsUnsolicitedSales = containsUnsolicitedSales;
            this.ContainsPromotionalContent = containsPromotionalContent;
            this.ContainsPhishingAttempt = containsPhishingAttempt;
            this.AnalysisRationale = analysisRationale;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no phishing was detected
        /// </summary>
        /// <value>True if no phishing was detected</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Phishing risk level (0.0 to 1.0)
        /// </summary>
        /// <value>Phishing risk level (0.0 to 1.0)</value>
        [DataMember(Name = "PhishingRiskLevel", EmitDefaultValue = false)]
        public double PhishingRiskLevel { get; set; }

        /// <summary>
        /// URL is a server-side request forgery threat
        /// </summary>
        /// <value>URL is a server-side request forgery threat</value>
        [DataMember(Name = "IsSsrfThreat", EmitDefaultValue = true)]
        public bool IsSsrfThreat { get; set; }

        /// <summary>
        /// URL contains phishing
        /// </summary>
        /// <value>URL contains phishing</value>
        [DataMember(Name = "ContainsPhishing", EmitDefaultValue = true)]
        public bool ContainsPhishing { get; set; }

        /// <summary>
        /// URL contains unsolicited sales
        /// </summary>
        /// <value>URL contains unsolicited sales</value>
        [DataMember(Name = "ContainsUnsolicitedSales", EmitDefaultValue = true)]
        public bool ContainsUnsolicitedSales { get; set; }

        /// <summary>
        /// URL contains promotional content
        /// </summary>
        /// <value>URL contains promotional content</value>
        [DataMember(Name = "ContainsPromotionalContent", EmitDefaultValue = true)]
        public bool ContainsPromotionalContent { get; set; }

        /// <summary>
        /// URL contains phishing attempt
        /// </summary>
        /// <value>URL contains phishing attempt</value>
        [DataMember(Name = "ContainsPhishingAttempt", EmitDefaultValue = true)]
        public bool ContainsPhishingAttempt { get; set; }

        /// <summary>
        /// Analysis rationale
        /// </summary>
        /// <value>Analysis rationale</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhishingDetectionUrlResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  PhishingRiskLevel: ").Append(PhishingRiskLevel).Append("\n");
            sb.Append("  IsSsrfThreat: ").Append(IsSsrfThreat).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("  ContainsUnsolicitedSales: ").Append(ContainsUnsolicitedSales).Append("\n");
            sb.Append("  ContainsPromotionalContent: ").Append(ContainsPromotionalContent).Append("\n");
            sb.Append("  ContainsPhishingAttempt: ").Append(ContainsPhishingAttempt).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
