/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Phishing detection configuration for text scanning
    /// </summary>
    [DataContract(Name = "PhishingDetectionTextConfig")]
    public partial class PhishingDetectionTextConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionTextConfig" /> class.
        /// </summary>
        /// <param name="enabled">Enable phishing detection.</param>
        /// <param name="textType">Type of text: TextMessage, UserMessage, SalesLead, EmailMessage, SupportCase, AppMessage, Other.</param>
        /// <param name="model">Model to use: Normal or Advanced.</param>
        /// <param name="allowUnsolicitedSales">Allow unsolicited sales content.</param>
        /// <param name="allowPromotionalContent">Allow promotional content.</param>
        /// <param name="allowWebUrls">Allow web URLs in content.</param>
        /// <param name="allowPhoneNumbers">Allow phone numbers in content.</param>
        /// <param name="allowEmailAddresses">Allow email addresses in content.</param>
        /// <param name="provideUrlAnalysis">Provide URL analysis details.</param>
        /// <param name="customPolicyID">Custom policy ID for managed instances.</param>
        /// <param name="provideAnalysisRationale">Provide analysis rationale in response.</param>
        /// <param name="fromName">Name of the sender.</param>
        /// <param name="toName">Name of the recipient.</param>
        /// <param name="fromPhoneNumber">Phone number of the sender.</param>
        /// <param name="toPhoneNumber">Phone number of the recipient.</param>
        /// <param name="fromEmailAddress">Email address of the sender.</param>
        /// <param name="toEmailAddress">Email address of the recipient.</param>
        public PhishingDetectionTextConfig(bool enabled = default(bool), string textType = default(string), string model = default(string), bool allowUnsolicitedSales = default(bool), bool allowPromotionalContent = default(bool), bool allowWebUrls = default(bool), bool allowPhoneNumbers = default(bool), bool allowEmailAddresses = default(bool), bool provideUrlAnalysis = default(bool), string customPolicyID = default(string), bool provideAnalysisRationale = default(bool), string fromName = default(string), string toName = default(string), string fromPhoneNumber = default(string), string toPhoneNumber = default(string), string fromEmailAddress = default(string), string toEmailAddress = default(string))
        {
            this.Enabled = enabled;
            this.TextType = textType;
            this.Model = model;
            this.AllowUnsolicitedSales = allowUnsolicitedSales;
            this.AllowPromotionalContent = allowPromotionalContent;
            this.AllowWebUrls = allowWebUrls;
            this.AllowPhoneNumbers = allowPhoneNumbers;
            this.AllowEmailAddresses = allowEmailAddresses;
            this.ProvideUrlAnalysis = provideUrlAnalysis;
            this.CustomPolicyID = customPolicyID;
            this.ProvideAnalysisRationale = provideAnalysisRationale;
            this.FromName = fromName;
            this.ToName = toName;
            this.FromPhoneNumber = fromPhoneNumber;
            this.ToPhoneNumber = toPhoneNumber;
            this.FromEmailAddress = fromEmailAddress;
            this.ToEmailAddress = toEmailAddress;
        }

        /// <summary>
        /// Enable phishing detection
        /// </summary>
        /// <value>Enable phishing detection</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Type of text: TextMessage, UserMessage, SalesLead, EmailMessage, SupportCase, AppMessage, Other
        /// </summary>
        /// <value>Type of text: TextMessage, UserMessage, SalesLead, EmailMessage, SupportCase, AppMessage, Other</value>
        /*
        <example>EmailMessage</example>
        */
        [DataMember(Name = "TextType", EmitDefaultValue = false)]
        public string TextType { get; set; }

        /// <summary>
        /// Model to use: Normal or Advanced
        /// </summary>
        /// <value>Model to use: Normal or Advanced</value>
        /*
        <example>Advanced</example>
        */
        [DataMember(Name = "Model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Allow unsolicited sales content
        /// </summary>
        /// <value>Allow unsolicited sales content</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowUnsolicitedSales", EmitDefaultValue = true)]
        public bool AllowUnsolicitedSales { get; set; }

        /// <summary>
        /// Allow promotional content
        /// </summary>
        /// <value>Allow promotional content</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowPromotionalContent", EmitDefaultValue = true)]
        public bool AllowPromotionalContent { get; set; }

        /// <summary>
        /// Allow web URLs in content
        /// </summary>
        /// <value>Allow web URLs in content</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowWebUrls", EmitDefaultValue = true)]
        public bool AllowWebUrls { get; set; }

        /// <summary>
        /// Allow phone numbers in content
        /// </summary>
        /// <value>Allow phone numbers in content</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowPhoneNumbers", EmitDefaultValue = true)]
        public bool AllowPhoneNumbers { get; set; }

        /// <summary>
        /// Allow email addresses in content
        /// </summary>
        /// <value>Allow email addresses in content</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowEmailAddresses", EmitDefaultValue = true)]
        public bool AllowEmailAddresses { get; set; }

        /// <summary>
        /// Provide URL analysis details
        /// </summary>
        /// <value>Provide URL analysis details</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "ProvideUrlAnalysis", EmitDefaultValue = true)]
        public bool ProvideUrlAnalysis { get; set; }

        /// <summary>
        /// Custom policy ID for managed instances
        /// </summary>
        /// <value>Custom policy ID for managed instances</value>
        [DataMember(Name = "CustomPolicyID", EmitDefaultValue = false)]
        public string CustomPolicyID { get; set; }

        /// <summary>
        /// Provide analysis rationale in response
        /// </summary>
        /// <value>Provide analysis rationale in response</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "ProvideAnalysisRationale", EmitDefaultValue = true)]
        public bool ProvideAnalysisRationale { get; set; }

        /// <summary>
        /// Name of the sender
        /// </summary>
        /// <value>Name of the sender</value>
        [DataMember(Name = "FromName", EmitDefaultValue = false)]
        public string FromName { get; set; }

        /// <summary>
        /// Name of the recipient
        /// </summary>
        /// <value>Name of the recipient</value>
        [DataMember(Name = "ToName", EmitDefaultValue = false)]
        public string ToName { get; set; }

        /// <summary>
        /// Phone number of the sender
        /// </summary>
        /// <value>Phone number of the sender</value>
        [DataMember(Name = "FromPhoneNumber", EmitDefaultValue = false)]
        public string FromPhoneNumber { get; set; }

        /// <summary>
        /// Phone number of the recipient
        /// </summary>
        /// <value>Phone number of the recipient</value>
        [DataMember(Name = "ToPhoneNumber", EmitDefaultValue = false)]
        public string ToPhoneNumber { get; set; }

        /// <summary>
        /// Email address of the sender
        /// </summary>
        /// <value>Email address of the sender</value>
        [DataMember(Name = "FromEmailAddress", EmitDefaultValue = false)]
        public string FromEmailAddress { get; set; }

        /// <summary>
        /// Email address of the recipient
        /// </summary>
        /// <value>Email address of the recipient</value>
        [DataMember(Name = "ToEmailAddress", EmitDefaultValue = false)]
        public string ToEmailAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhishingDetectionTextConfig {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  TextType: ").Append(TextType).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  AllowUnsolicitedSales: ").Append(AllowUnsolicitedSales).Append("\n");
            sb.Append("  AllowPromotionalContent: ").Append(AllowPromotionalContent).Append("\n");
            sb.Append("  AllowWebUrls: ").Append(AllowWebUrls).Append("\n");
            sb.Append("  AllowPhoneNumbers: ").Append(AllowPhoneNumbers).Append("\n");
            sb.Append("  AllowEmailAddresses: ").Append(AllowEmailAddresses).Append("\n");
            sb.Append("  ProvideUrlAnalysis: ").Append(ProvideUrlAnalysis).Append("\n");
            sb.Append("  CustomPolicyID: ").Append(CustomPolicyID).Append("\n");
            sb.Append("  ProvideAnalysisRationale: ").Append(ProvideAnalysisRationale).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ToName: ").Append(ToName).Append("\n");
            sb.Append("  FromPhoneNumber: ").Append(FromPhoneNumber).Append("\n");
            sb.Append("  ToPhoneNumber: ").Append(ToPhoneNumber).Append("\n");
            sb.Append("  FromEmailAddress: ").Append(FromEmailAddress).Append("\n");
            sb.Append("  ToEmailAddress: ").Append(ToEmailAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
