/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Phishing detection result for text scanning
    /// </summary>
    [DataContract(Name = "PhishingDetectionTextResult")]
    public partial class PhishingDetectionTextResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionTextResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no phishing was detected.</param>
        /// <param name="containsPhishing">Text contains phishing.</param>
        /// <param name="containsUnsolicitedSales">Text contains unsolicited sales.</param>
        /// <param name="containsPromotionalContent">Text contains promotional content.</param>
        /// <param name="containsWebUrls">Text contains web URLs.</param>
        /// <param name="containsPhoneNumbers">Text contains phone numbers.</param>
        /// <param name="containsEmailAddresses">Text contains email addresses.</param>
        /// <param name="confidenceLevel">Confidence level (0.0 to 1.0).</param>
        /// <param name="analysisRationale">Analysis rationale.</param>
        /// <param name="unsafeUrls">List of unsafe URLs found.</param>
        public PhishingDetectionTextResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), bool containsPhishing = default(bool), bool containsUnsolicitedSales = default(bool), bool containsPromotionalContent = default(bool), bool containsWebUrls = default(bool), bool containsPhoneNumbers = default(bool), bool containsEmailAddresses = default(bool), double confidenceLevel = default(double), string analysisRationale = default(string), List<UnsafeUrlInfo> unsafeUrls = default(List<UnsafeUrlInfo>))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.ContainsPhishing = containsPhishing;
            this.ContainsUnsolicitedSales = containsUnsolicitedSales;
            this.ContainsPromotionalContent = containsPromotionalContent;
            this.ContainsWebUrls = containsWebUrls;
            this.ContainsPhoneNumbers = containsPhoneNumbers;
            this.ContainsEmailAddresses = containsEmailAddresses;
            this.ConfidenceLevel = confidenceLevel;
            this.AnalysisRationale = analysisRationale;
            this.UnsafeUrls = unsafeUrls;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no phishing was detected
        /// </summary>
        /// <value>True if no phishing was detected</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Text contains phishing
        /// </summary>
        /// <value>Text contains phishing</value>
        [DataMember(Name = "ContainsPhishing", EmitDefaultValue = true)]
        public bool ContainsPhishing { get; set; }

        /// <summary>
        /// Text contains unsolicited sales
        /// </summary>
        /// <value>Text contains unsolicited sales</value>
        [DataMember(Name = "ContainsUnsolicitedSales", EmitDefaultValue = true)]
        public bool ContainsUnsolicitedSales { get; set; }

        /// <summary>
        /// Text contains promotional content
        /// </summary>
        /// <value>Text contains promotional content</value>
        [DataMember(Name = "ContainsPromotionalContent", EmitDefaultValue = true)]
        public bool ContainsPromotionalContent { get; set; }

        /// <summary>
        /// Text contains web URLs
        /// </summary>
        /// <value>Text contains web URLs</value>
        [DataMember(Name = "ContainsWebUrls", EmitDefaultValue = true)]
        public bool ContainsWebUrls { get; set; }

        /// <summary>
        /// Text contains phone numbers
        /// </summary>
        /// <value>Text contains phone numbers</value>
        [DataMember(Name = "ContainsPhoneNumbers", EmitDefaultValue = true)]
        public bool ContainsPhoneNumbers { get; set; }

        /// <summary>
        /// Text contains email addresses
        /// </summary>
        /// <value>Text contains email addresses</value>
        [DataMember(Name = "ContainsEmailAddresses", EmitDefaultValue = true)]
        public bool ContainsEmailAddresses { get; set; }

        /// <summary>
        /// Confidence level (0.0 to 1.0)
        /// </summary>
        /// <value>Confidence level (0.0 to 1.0)</value>
        [DataMember(Name = "ConfidenceLevel", EmitDefaultValue = false)]
        public double ConfidenceLevel { get; set; }

        /// <summary>
        /// Analysis rationale
        /// </summary>
        /// <value>Analysis rationale</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// List of unsafe URLs found
        /// </summary>
        /// <value>List of unsafe URLs found</value>
        [DataMember(Name = "UnsafeUrls", EmitDefaultValue = false)]
        public List<UnsafeUrlInfo> UnsafeUrls { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhishingDetectionTextResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("  ContainsUnsolicitedSales: ").Append(ContainsUnsolicitedSales).Append("\n");
            sb.Append("  ContainsPromotionalContent: ").Append(ContainsPromotionalContent).Append("\n");
            sb.Append("  ContainsWebUrls: ").Append(ContainsWebUrls).Append("\n");
            sb.Append("  ContainsPhoneNumbers: ").Append(ContainsPhoneNumbers).Append("\n");
            sb.Append("  ContainsEmailAddresses: ").Append(ContainsEmailAddresses).Append("\n");
            sb.Append("  ConfidenceLevel: ").Append(ConfidenceLevel).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("  UnsafeUrls: ").Append(UnsafeUrls).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
