/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Policy enforcement configuration with custom rules
    /// </summary>
    [DataContract(Name = "PolicyEnforcementConfig")]
    public partial class PolicyEnforcementConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyEnforcementConfig" /> class.
        /// </summary>
        /// <param name="enabled">Enable policy enforcement.</param>
        /// <param name="rules">List of policy rules to enforce.</param>
        public PolicyEnforcementConfig(bool enabled = default(bool), List<PolicyRule> rules = default(List<PolicyRule>))
        {
            this.Enabled = enabled;
            this.Rules = rules;
        }

        /// <summary>
        /// Enable policy enforcement
        /// </summary>
        /// <value>Enable policy enforcement</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// List of policy rules to enforce
        /// </summary>
        /// <value>List of policy rules to enforce</value>
        [DataMember(Name = "Rules", EmitDefaultValue = false)]
        public List<PolicyRule> Rules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PolicyEnforcementConfig {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Rules: ").Append(Rules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
