/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Policy enforcement result
    /// </summary>
    [DataContract(Name = "PolicyEnforcementResult")]
    public partial class PolicyEnforcementResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyEnforcementResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no policy violations were found.</param>
        /// <param name="riskScore">Overall risk score (0.0 to 1.0).</param>
        /// <param name="ruleViolations">List of rule violations found.</param>
        /// <param name="skipped">Scan was skipped.</param>
        /// <param name="skipReason">Reason the scan was skipped.</param>
        public PolicyEnforcementResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), double riskScore = default(double), List<PolicyRuleViolation> ruleViolations = default(List<PolicyRuleViolation>), bool skipped = default(bool), string skipReason = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.RiskScore = riskScore;
            this.RuleViolations = ruleViolations;
            this.Skipped = skipped;
            this.SkipReason = skipReason;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no policy violations were found
        /// </summary>
        /// <value>True if no policy violations were found</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Overall risk score (0.0 to 1.0)
        /// </summary>
        /// <value>Overall risk score (0.0 to 1.0)</value>
        [DataMember(Name = "RiskScore", EmitDefaultValue = false)]
        public double RiskScore { get; set; }

        /// <summary>
        /// List of rule violations found
        /// </summary>
        /// <value>List of rule violations found</value>
        [DataMember(Name = "RuleViolations", EmitDefaultValue = false)]
        public List<PolicyRuleViolation> RuleViolations { get; set; }

        /// <summary>
        /// Scan was skipped
        /// </summary>
        /// <value>Scan was skipped</value>
        [DataMember(Name = "Skipped", EmitDefaultValue = true)]
        public bool Skipped { get; set; }

        /// <summary>
        /// Reason the scan was skipped
        /// </summary>
        /// <value>Reason the scan was skipped</value>
        [DataMember(Name = "SkipReason", EmitDefaultValue = false)]
        public string SkipReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PolicyEnforcementResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  RiskScore: ").Append(RiskScore).Append("\n");
            sb.Append("  RuleViolations: ").Append(RuleViolations).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  SkipReason: ").Append(SkipReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
