/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// A single policy rule
    /// </summary>
    [DataContract(Name = "PolicyRule")]
    public partial class PolicyRule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyRule" /> class.
        /// </summary>
        /// <param name="ruleId">Unique rule identifier.</param>
        /// <param name="ruleType">Rule type: ALLOW or DENY.</param>
        /// <param name="ruleDescription">Natural language description of the policy rule.</param>
        public PolicyRule(string ruleId = default(string), string ruleType = default(string), string ruleDescription = default(string))
        {
            this.RuleId = ruleId;
            this.RuleType = ruleType;
            this.RuleDescription = ruleDescription;
        }

        /// <summary>
        /// Unique rule identifier
        /// </summary>
        /// <value>Unique rule identifier</value>
        /*
        <example>RULE-001</example>
        */
        [DataMember(Name = "RuleId", EmitDefaultValue = false)]
        public string RuleId { get; set; }

        /// <summary>
        /// Rule type: ALLOW or DENY
        /// </summary>
        /// <value>Rule type: ALLOW or DENY</value>
        /*
        <example>DENY</example>
        */
        [DataMember(Name = "RuleType", EmitDefaultValue = false)]
        public string RuleType { get; set; }

        /// <summary>
        /// Natural language description of the policy rule
        /// </summary>
        /// <value>Natural language description of the policy rule</value>
        /*
        <example>Documents must not contain financial advice</example>
        */
        [DataMember(Name = "RuleDescription", EmitDefaultValue = false)]
        public string RuleDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PolicyRule {\n");
            sb.Append("  RuleId: ").Append(RuleId).Append("\n");
            sb.Append("  RuleType: ").Append(RuleType).Append("\n");
            sb.Append("  RuleDescription: ").Append(RuleDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
