/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// A single policy rule violation
    /// </summary>
    [DataContract(Name = "PolicyRuleViolation")]
    public partial class PolicyRuleViolation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyRuleViolation" /> class.
        /// </summary>
        /// <param name="ruleId">ID of the violated rule.</param>
        /// <param name="ruleViolationRiskScore">Risk score for this violation (0.0 to 1.0).</param>
        /// <param name="ruleViolationRationale">Rationale for the violation.</param>
        public PolicyRuleViolation(string ruleId = default(string), double ruleViolationRiskScore = default(double), string ruleViolationRationale = default(string))
        {
            this.RuleId = ruleId;
            this.RuleViolationRiskScore = ruleViolationRiskScore;
            this.RuleViolationRationale = ruleViolationRationale;
        }

        /// <summary>
        /// ID of the violated rule
        /// </summary>
        /// <value>ID of the violated rule</value>
        [DataMember(Name = "RuleId", EmitDefaultValue = false)]
        public string RuleId { get; set; }

        /// <summary>
        /// Risk score for this violation (0.0 to 1.0)
        /// </summary>
        /// <value>Risk score for this violation (0.0 to 1.0)</value>
        [DataMember(Name = "RuleViolationRiskScore", EmitDefaultValue = false)]
        public double RuleViolationRiskScore { get; set; }

        /// <summary>
        /// Rationale for the violation
        /// </summary>
        /// <value>Rationale for the violation</value>
        [DataMember(Name = "RuleViolationRationale", EmitDefaultValue = false)]
        public string RuleViolationRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PolicyRuleViolation {\n");
            sb.Append("  RuleId: ").Append(RuleId).Append("\n");
            sb.Append("  RuleViolationRiskScore: ").Append(RuleViolationRiskScore).Append("\n");
            sb.Append("  RuleViolationRationale: ").Append(RuleViolationRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
