/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Spam detection result
    /// </summary>
    [DataContract(Name = "SpamDetectionResult")]
    public partial class SpamDetectionResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no spam was detected.</param>
        /// <param name="spamRiskLevel">Spam risk level (0.0 to 1.0).</param>
        /// <param name="containsSpam">Content contains spam.</param>
        /// <param name="containsUnsolicitedSales">Content contains unsolicited sales.</param>
        /// <param name="containsPromotionalContent">Content contains promotional material.</param>
        /// <param name="containsPhishingAttempt">Content contains phishing attempt.</param>
        /// <param name="analysisRationale">Analysis rationale.</param>
        /// <param name="skipped">Scan was skipped.</param>
        /// <param name="skipReason">Reason the scan was skipped.</param>
        public SpamDetectionResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), double spamRiskLevel = default(double), bool containsSpam = default(bool), bool containsUnsolicitedSales = default(bool), bool containsPromotionalContent = default(bool), bool containsPhishingAttempt = default(bool), string analysisRationale = default(string), bool skipped = default(bool), string skipReason = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.SpamRiskLevel = spamRiskLevel;
            this.ContainsSpam = containsSpam;
            this.ContainsUnsolicitedSales = containsUnsolicitedSales;
            this.ContainsPromotionalContent = containsPromotionalContent;
            this.ContainsPhishingAttempt = containsPhishingAttempt;
            this.AnalysisRationale = analysisRationale;
            this.Skipped = skipped;
            this.SkipReason = skipReason;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no spam was detected
        /// </summary>
        /// <value>True if no spam was detected</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Spam risk level (0.0 to 1.0)
        /// </summary>
        /// <value>Spam risk level (0.0 to 1.0)</value>
        [DataMember(Name = "SpamRiskLevel", EmitDefaultValue = false)]
        public double SpamRiskLevel { get; set; }

        /// <summary>
        /// Content contains spam
        /// </summary>
        /// <value>Content contains spam</value>
        [DataMember(Name = "ContainsSpam", EmitDefaultValue = true)]
        public bool ContainsSpam { get; set; }

        /// <summary>
        /// Content contains unsolicited sales
        /// </summary>
        /// <value>Content contains unsolicited sales</value>
        [DataMember(Name = "ContainsUnsolicitedSales", EmitDefaultValue = true)]
        public bool ContainsUnsolicitedSales { get; set; }

        /// <summary>
        /// Content contains promotional material
        /// </summary>
        /// <value>Content contains promotional material</value>
        [DataMember(Name = "ContainsPromotionalContent", EmitDefaultValue = true)]
        public bool ContainsPromotionalContent { get; set; }

        /// <summary>
        /// Content contains phishing attempt
        /// </summary>
        /// <value>Content contains phishing attempt</value>
        [DataMember(Name = "ContainsPhishingAttempt", EmitDefaultValue = true)]
        public bool ContainsPhishingAttempt { get; set; }

        /// <summary>
        /// Analysis rationale
        /// </summary>
        /// <value>Analysis rationale</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Scan was skipped
        /// </summary>
        /// <value>Scan was skipped</value>
        [DataMember(Name = "Skipped", EmitDefaultValue = true)]
        public bool Skipped { get; set; }

        /// <summary>
        /// Reason the scan was skipped
        /// </summary>
        /// <value>Reason the scan was skipped</value>
        [DataMember(Name = "SkipReason", EmitDefaultValue = false)]
        public string SkipReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpamDetectionResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  SpamRiskLevel: ").Append(SpamRiskLevel).Append("\n");
            sb.Append("  ContainsSpam: ").Append(ContainsSpam).Append("\n");
            sb.Append("  ContainsUnsolicitedSales: ").Append(ContainsUnsolicitedSales).Append("\n");
            sb.Append("  ContainsPromotionalContent: ").Append(ContainsPromotionalContent).Append("\n");
            sb.Append("  ContainsPhishingAttempt: ").Append(ContainsPhishingAttempt).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  SkipReason: ").Append(SkipReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
