/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Spam detection configuration
    /// </summary>
    [DataContract(Name = "SpamDetectionConfig")]
    public partial class SpamDetectionConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionConfig" /> class.
        /// </summary>
        /// <param name="enabled">Enable spam detection.</param>
        /// <param name="model">Model to use: Normal or Advanced.</param>
        /// <param name="allowUnsolicitedSales">Allow unsolicited sales content.</param>
        /// <param name="allowPromotionalContent">Allow promotional content.</param>
        /// <param name="allowPhishing">Allow phishing content.</param>
        public SpamDetectionConfig(bool enabled = default(bool), string model = default(string), bool allowUnsolicitedSales = default(bool), bool allowPromotionalContent = default(bool), bool allowPhishing = default(bool))
        {
            this.Enabled = enabled;
            this.Model = model;
            this.AllowUnsolicitedSales = allowUnsolicitedSales;
            this.AllowPromotionalContent = allowPromotionalContent;
            this.AllowPhishing = allowPhishing;
        }

        /// <summary>
        /// Enable spam detection
        /// </summary>
        /// <value>Enable spam detection</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Model to use: Normal or Advanced
        /// </summary>
        /// <value>Model to use: Normal or Advanced</value>
        /*
        <example>Advanced</example>
        */
        [DataMember(Name = "Model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Allow unsolicited sales content
        /// </summary>
        /// <value>Allow unsolicited sales content</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowUnsolicitedSales", EmitDefaultValue = true)]
        public bool AllowUnsolicitedSales { get; set; }

        /// <summary>
        /// Allow promotional content
        /// </summary>
        /// <value>Allow promotional content</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowPromotionalContent", EmitDefaultValue = true)]
        public bool AllowPromotionalContent { get; set; }

        /// <summary>
        /// Allow phishing content
        /// </summary>
        /// <value>Allow phishing content</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPhishing", EmitDefaultValue = true)]
        public bool AllowPhishing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpamDetectionConfig {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  AllowUnsolicitedSales: ").Append(AllowUnsolicitedSales).Append("\n");
            sb.Append("  AllowPromotionalContent: ").Append(AllowPromotionalContent).Append("\n");
            sb.Append("  AllowPhishing: ").Append(AllowPhishing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
