/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Individual scan results for a text scan
    /// </summary>
    [DataContract(Name = "TextScanResults")]
    public partial class TextScanResults : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextScanResults" /> class.
        /// </summary>
        /// <param name="virusScan">virusScan.</param>
        /// <param name="phishingDetection">phishingDetection.</param>
        /// <param name="spamDetection">spamDetection.</param>
        /// <param name="dlpDetection">dlpDetection.</param>
        /// <param name="policyEnforcement">policyEnforcement.</param>
        public TextScanResults(VirusScanResult virusScan = default(VirusScanResult), PhishingDetectionTextResult phishingDetection = default(PhishingDetectionTextResult), SpamDetectionResult spamDetection = default(SpamDetectionResult), DlpDetectionResult dlpDetection = default(DlpDetectionResult), PolicyEnforcementResult policyEnforcement = default(PolicyEnforcementResult))
        {
            this.VirusScan = virusScan;
            this.PhishingDetection = phishingDetection;
            this.SpamDetection = spamDetection;
            this.DlpDetection = dlpDetection;
            this.PolicyEnforcement = policyEnforcement;
        }

        /// <summary>
        /// Gets or Sets VirusScan
        /// </summary>
        [DataMember(Name = "VirusScan", EmitDefaultValue = false)]
        public VirusScanResult VirusScan { get; set; }

        /// <summary>
        /// Gets or Sets PhishingDetection
        /// </summary>
        [DataMember(Name = "PhishingDetection", EmitDefaultValue = false)]
        public PhishingDetectionTextResult PhishingDetection { get; set; }

        /// <summary>
        /// Gets or Sets SpamDetection
        /// </summary>
        [DataMember(Name = "SpamDetection", EmitDefaultValue = false)]
        public SpamDetectionResult SpamDetection { get; set; }

        /// <summary>
        /// Gets or Sets DlpDetection
        /// </summary>
        [DataMember(Name = "DlpDetection", EmitDefaultValue = false)]
        public DlpDetectionResult DlpDetection { get; set; }

        /// <summary>
        /// Gets or Sets PolicyEnforcement
        /// </summary>
        [DataMember(Name = "PolicyEnforcement", EmitDefaultValue = false)]
        public PolicyEnforcementResult PolicyEnforcement { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TextScanResults {\n");
            sb.Append("  VirusScan: ").Append(VirusScan).Append("\n");
            sb.Append("  PhishingDetection: ").Append(PhishingDetection).Append("\n");
            sb.Append("  SpamDetection: ").Append(SpamDetection).Append("\n");
            sb.Append("  DlpDetection: ").Append(DlpDetection).Append("\n");
            sb.Append("  PolicyEnforcement: ").Append(PolicyEnforcement).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
