/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Information about an unsafe URL
    /// </summary>
    [DataContract(Name = "UnsafeUrlInfo")]
    public partial class UnsafeUrlInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsafeUrlInfo" /> class.
        /// </summary>
        /// <param name="url">The URL.</param>
        /// <param name="cleanResult">True if URL is clean.</param>
        /// <param name="isSsrfThreat">URL is an SSRF threat.</param>
        /// <param name="containsPhishing">URL contains phishing.</param>
        public UnsafeUrlInfo(string url = default(string), bool cleanResult = default(bool), bool isSsrfThreat = default(bool), bool containsPhishing = default(bool))
        {
            this.Url = url;
            this.CleanResult = cleanResult;
            this.IsSsrfThreat = isSsrfThreat;
            this.ContainsPhishing = containsPhishing;
        }

        /// <summary>
        /// The URL
        /// </summary>
        /// <value>The URL</value>
        [DataMember(Name = "Url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// True if URL is clean
        /// </summary>
        /// <value>True if URL is clean</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// URL is an SSRF threat
        /// </summary>
        /// <value>URL is an SSRF threat</value>
        [DataMember(Name = "IsSsrfThreat", EmitDefaultValue = true)]
        public bool IsSsrfThreat { get; set; }

        /// <summary>
        /// URL contains phishing
        /// </summary>
        /// <value>URL contains phishing</value>
        [DataMember(Name = "ContainsPhishing", EmitDefaultValue = true)]
        public bool ContainsPhishing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnsafeUrlInfo {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  IsSsrfThreat: ").Append(IsSsrfThreat).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
