/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Individual scan results for a URL scan
    /// </summary>
    [DataContract(Name = "UrlScanResults")]
    public partial class UrlScanResults : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UrlScanResults" /> class.
        /// </summary>
        /// <param name="virusScan">virusScan.</param>
        /// <param name="phishingDetection">phishingDetection.</param>
        /// <param name="policyEnforcement">policyEnforcement.</param>
        /// <param name="contentScanning">contentScanning.</param>
        public UrlScanResults(VirusScanUrlResult virusScan = default(VirusScanUrlResult), PhishingDetectionUrlResult phishingDetection = default(PhishingDetectionUrlResult), PolicyEnforcementResult policyEnforcement = default(PolicyEnforcementResult), ContentScanningResult contentScanning = default(ContentScanningResult))
        {
            this.VirusScan = virusScan;
            this.PhishingDetection = phishingDetection;
            this.PolicyEnforcement = policyEnforcement;
            this.ContentScanning = contentScanning;
        }

        /// <summary>
        /// Gets or Sets VirusScan
        /// </summary>
        [DataMember(Name = "VirusScan", EmitDefaultValue = false)]
        public VirusScanUrlResult VirusScan { get; set; }

        /// <summary>
        /// Gets or Sets PhishingDetection
        /// </summary>
        [DataMember(Name = "PhishingDetection", EmitDefaultValue = false)]
        public PhishingDetectionUrlResult PhishingDetection { get; set; }

        /// <summary>
        /// Gets or Sets PolicyEnforcement
        /// </summary>
        [DataMember(Name = "PolicyEnforcement", EmitDefaultValue = false)]
        public PolicyEnforcementResult PolicyEnforcement { get; set; }

        /// <summary>
        /// Gets or Sets ContentScanning
        /// </summary>
        [DataMember(Name = "ContentScanning", EmitDefaultValue = false)]
        public ContentScanningResult ContentScanning { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UrlScanResults {\n");
            sb.Append("  VirusScan: ").Append(VirusScan).Append("\n");
            sb.Append("  PhishingDetection: ").Append(PhishingDetection).Append("\n");
            sb.Append("  PolicyEnforcement: ").Append(PolicyEnforcement).Append("\n");
            sb.Append("  ContentScanning: ").Append(ContentScanning).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
