/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// URL-specific virus scan configuration
    /// </summary>
    [DataContract(Name = "UrlVirusScanConfig")]
    public partial class UrlVirusScanConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UrlVirusScanConfig" /> class.
        /// </summary>
        /// <param name="enabled">Enable virus scanning.</param>
        public UrlVirusScanConfig(bool enabled = default(bool))
        {
            this.Enabled = enabled;
        }

        /// <summary>
        /// Enable virus scanning
        /// </summary>
        /// <value>Enable virus scanning</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UrlVirusScanConfig {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
