/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Virus scan result for URL scanning
    /// </summary>
    [DataContract(Name = "VirusScanUrlResult")]
    public partial class VirusScanUrlResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirusScanUrlResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no threats were found.</param>
        /// <param name="websiteThreatType">Website threat type: None, Malware, Phishing, ForcedDownload, UnableToConnect.</param>
        /// <param name="foundViruses">List of viruses found.</param>
        /// <param name="websiteHttpResponseCode">HTTP response code from the website.</param>
        public VirusScanUrlResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), string websiteThreatType = default(string), List<VirusFound> foundViruses = default(List<VirusFound>), int websiteHttpResponseCode = default(int))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.WebsiteThreatType = websiteThreatType;
            this.FoundViruses = foundViruses;
            this.WebsiteHttpResponseCode = websiteHttpResponseCode;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no threats were found
        /// </summary>
        /// <value>True if no threats were found</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Website threat type: None, Malware, Phishing, ForcedDownload, UnableToConnect
        /// </summary>
        /// <value>Website threat type: None, Malware, Phishing, ForcedDownload, UnableToConnect</value>
        [DataMember(Name = "WebsiteThreatType", EmitDefaultValue = false)]
        public string WebsiteThreatType { get; set; }

        /// <summary>
        /// List of viruses found
        /// </summary>
        /// <value>List of viruses found</value>
        [DataMember(Name = "FoundViruses", EmitDefaultValue = false)]
        public List<VirusFound> FoundViruses { get; set; }

        /// <summary>
        /// HTTP response code from the website
        /// </summary>
        /// <value>HTTP response code from the website</value>
        [DataMember(Name = "WebsiteHttpResponseCode", EmitDefaultValue = false)]
        public int WebsiteHttpResponseCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirusScanUrlResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  WebsiteThreatType: ").Append(WebsiteThreatType).Append("\n");
            sb.Append("  FoundViruses: ").Append(FoundViruses).Append("\n");
            sb.Append("  WebsiteHttpResponseCode: ").Append(WebsiteHttpResponseCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
