/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Virus scan configuration
    /// </summary>
    [DataContract(Name = "VirusScanConfig")]
    public partial class VirusScanConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirusScanConfig" /> class.
        /// </summary>
        /// <param name="enabled">Enable virus scanning.</param>
        /// <param name="allowExecutables">Allow executable files.</param>
        /// <param name="allowInvalidFiles">Allow invalid files.</param>
        /// <param name="allowScripts">Allow script files.</param>
        /// <param name="allowPasswordProtectedFiles">Allow password-protected files.</param>
        /// <param name="allowMacros">Allow files containing macros.</param>
        /// <param name="allowXmlExternalEntities">Allow XML external entities.</param>
        /// <param name="allowInsecureDeserialization">Allow insecure deserialization.</param>
        /// <param name="allowHtml">Allow HTML content.</param>
        /// <param name="allowUnsafeArchives">Allow unsafe archives.</param>
        /// <param name="allowOleEmbeddedObject">Allow OLE embedded objects.</param>
        /// <param name="allowUnwantedAction">Allow unwanted actions.</param>
        /// <param name="restrictFileTypes">Restrict to specific file types (comma-separated extensions).</param>
        /// <param name="options">Comma-separated scan options.</param>
        public VirusScanConfig(bool enabled = default(bool), bool allowExecutables = default(bool), bool allowInvalidFiles = default(bool), bool allowScripts = default(bool), bool allowPasswordProtectedFiles = default(bool), bool allowMacros = default(bool), bool allowXmlExternalEntities = default(bool), bool allowInsecureDeserialization = default(bool), bool allowHtml = default(bool), bool allowUnsafeArchives = default(bool), bool allowOleEmbeddedObject = default(bool), bool allowUnwantedAction = default(bool), string restrictFileTypes = default(string), string options = default(string))
        {
            this.Enabled = enabled;
            this.AllowExecutables = allowExecutables;
            this.AllowInvalidFiles = allowInvalidFiles;
            this.AllowScripts = allowScripts;
            this.AllowPasswordProtectedFiles = allowPasswordProtectedFiles;
            this.AllowMacros = allowMacros;
            this.AllowXmlExternalEntities = allowXmlExternalEntities;
            this.AllowInsecureDeserialization = allowInsecureDeserialization;
            this.AllowHtml = allowHtml;
            this.AllowUnsafeArchives = allowUnsafeArchives;
            this.AllowOleEmbeddedObject = allowOleEmbeddedObject;
            this.AllowUnwantedAction = allowUnwantedAction;
            this.RestrictFileTypes = restrictFileTypes;
            this.Options = options;
        }

        /// <summary>
        /// Enable virus scanning
        /// </summary>
        /// <value>Enable virus scanning</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Allow executable files
        /// </summary>
        /// <value>Allow executable files</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowExecutables", EmitDefaultValue = true)]
        public bool AllowExecutables { get; set; }

        /// <summary>
        /// Allow invalid files
        /// </summary>
        /// <value>Allow invalid files</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowInvalidFiles", EmitDefaultValue = true)]
        public bool AllowInvalidFiles { get; set; }

        /// <summary>
        /// Allow script files
        /// </summary>
        /// <value>Allow script files</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowScripts", EmitDefaultValue = true)]
        public bool AllowScripts { get; set; }

        /// <summary>
        /// Allow password-protected files
        /// </summary>
        /// <value>Allow password-protected files</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPasswordProtectedFiles", EmitDefaultValue = true)]
        public bool AllowPasswordProtectedFiles { get; set; }

        /// <summary>
        /// Allow files containing macros
        /// </summary>
        /// <value>Allow files containing macros</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowMacros", EmitDefaultValue = true)]
        public bool AllowMacros { get; set; }

        /// <summary>
        /// Allow XML external entities
        /// </summary>
        /// <value>Allow XML external entities</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowXmlExternalEntities", EmitDefaultValue = true)]
        public bool AllowXmlExternalEntities { get; set; }

        /// <summary>
        /// Allow insecure deserialization
        /// </summary>
        /// <value>Allow insecure deserialization</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowInsecureDeserialization", EmitDefaultValue = true)]
        public bool AllowInsecureDeserialization { get; set; }

        /// <summary>
        /// Allow HTML content
        /// </summary>
        /// <value>Allow HTML content</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowHtml", EmitDefaultValue = true)]
        public bool AllowHtml { get; set; }

        /// <summary>
        /// Allow unsafe archives
        /// </summary>
        /// <value>Allow unsafe archives</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowUnsafeArchives", EmitDefaultValue = true)]
        public bool AllowUnsafeArchives { get; set; }

        /// <summary>
        /// Allow OLE embedded objects
        /// </summary>
        /// <value>Allow OLE embedded objects</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowOleEmbeddedObject", EmitDefaultValue = true)]
        public bool AllowOleEmbeddedObject { get; set; }

        /// <summary>
        /// Allow unwanted actions
        /// </summary>
        /// <value>Allow unwanted actions</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowUnwantedAction", EmitDefaultValue = true)]
        public bool AllowUnwantedAction { get; set; }

        /// <summary>
        /// Restrict to specific file types (comma-separated extensions)
        /// </summary>
        /// <value>Restrict to specific file types (comma-separated extensions)</value>
        /*
        <example>.pdf,.docx,.png</example>
        */
        [DataMember(Name = "RestrictFileTypes", EmitDefaultValue = false)]
        public string RestrictFileTypes { get; set; }

        /// <summary>
        /// Comma-separated scan options
        /// </summary>
        /// <value>Comma-separated scan options</value>
        [DataMember(Name = "Options", EmitDefaultValue = false)]
        public string Options { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirusScanConfig {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  AllowExecutables: ").Append(AllowExecutables).Append("\n");
            sb.Append("  AllowInvalidFiles: ").Append(AllowInvalidFiles).Append("\n");
            sb.Append("  AllowScripts: ").Append(AllowScripts).Append("\n");
            sb.Append("  AllowPasswordProtectedFiles: ").Append(AllowPasswordProtectedFiles).Append("\n");
            sb.Append("  AllowMacros: ").Append(AllowMacros).Append("\n");
            sb.Append("  AllowXmlExternalEntities: ").Append(AllowXmlExternalEntities).Append("\n");
            sb.Append("  AllowInsecureDeserialization: ").Append(AllowInsecureDeserialization).Append("\n");
            sb.Append("  AllowHtml: ").Append(AllowHtml).Append("\n");
            sb.Append("  AllowUnsafeArchives: ").Append(AllowUnsafeArchives).Append("\n");
            sb.Append("  AllowOleEmbeddedObject: ").Append(AllowOleEmbeddedObject).Append("\n");
            sb.Append("  AllowUnwantedAction: ").Append(AllowUnwantedAction).Append("\n");
            sb.Append("  RestrictFileTypes: ").Append(RestrictFileTypes).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
