/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Virus scan result
    /// </summary>
    [DataContract(Name = "VirusScanResult")]
    public partial class VirusScanResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirusScanResult" /> class.
        /// </summary>
        /// <param name="enabled">Whether this scan was enabled.</param>
        /// <param name="successful">Whether this scan completed successfully.</param>
        /// <param name="cleanResult">True if no threats were found.</param>
        /// <param name="containsExecutable">Contains executable content.</param>
        /// <param name="containsInvalidFile">Contains invalid file structure.</param>
        /// <param name="containsScript">Contains script content.</param>
        /// <param name="containsPasswordProtectedFile">File is password-protected.</param>
        /// <param name="containsRestrictedFileFormat">File format is restricted.</param>
        /// <param name="containsMacros">Contains macro code.</param>
        /// <param name="containsXmlExternalEntities">Contains XML external entities.</param>
        /// <param name="containsInsecureDeserialization">Contains insecure deserialization.</param>
        /// <param name="containsHtml">Contains HTML content.</param>
        /// <param name="containsUnsafeArchive">Contains unsafe archive structure.</param>
        /// <param name="containsOleEmbeddedObject">Contains OLE embedded objects.</param>
        /// <param name="containsUnwantedAction">Contains unwanted actions.</param>
        /// <param name="verifiedFileFormat">Content-verified file format.</param>
        /// <param name="foundViruses">List of viruses found.</param>
        /// <param name="contentInformation">contentInformation.</param>
        /// <param name="errorMessage">Error message if the scan failed.</param>
        public VirusScanResult(bool enabled = default(bool), bool successful = default(bool), bool cleanResult = default(bool), bool containsExecutable = default(bool), bool containsInvalidFile = default(bool), bool containsScript = default(bool), bool containsPasswordProtectedFile = default(bool), bool containsRestrictedFileFormat = default(bool), bool containsMacros = default(bool), bool containsXmlExternalEntities = default(bool), bool containsInsecureDeserialization = default(bool), bool containsHtml = default(bool), bool containsUnsafeArchive = default(bool), bool containsOleEmbeddedObject = default(bool), bool containsUnwantedAction = default(bool), string verifiedFileFormat = default(string), List<VirusFound> foundViruses = default(List<VirusFound>), VirusScanContentInfo contentInformation = default(VirusScanContentInfo), string errorMessage = default(string))
        {
            this.Enabled = enabled;
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.ContainsExecutable = containsExecutable;
            this.ContainsInvalidFile = containsInvalidFile;
            this.ContainsScript = containsScript;
            this.ContainsPasswordProtectedFile = containsPasswordProtectedFile;
            this.ContainsRestrictedFileFormat = containsRestrictedFileFormat;
            this.ContainsMacros = containsMacros;
            this.ContainsXmlExternalEntities = containsXmlExternalEntities;
            this.ContainsInsecureDeserialization = containsInsecureDeserialization;
            this.ContainsHtml = containsHtml;
            this.ContainsUnsafeArchive = containsUnsafeArchive;
            this.ContainsOleEmbeddedObject = containsOleEmbeddedObject;
            this.ContainsUnwantedAction = containsUnwantedAction;
            this.VerifiedFileFormat = verifiedFileFormat;
            this.FoundViruses = foundViruses;
            this.ContentInformation = contentInformation;
            this.ErrorMessage = errorMessage;
        }

        /// <summary>
        /// Whether this scan was enabled
        /// </summary>
        /// <value>Whether this scan was enabled</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether this scan completed successfully
        /// </summary>
        /// <value>Whether this scan completed successfully</value>
        [DataMember(Name = "Successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// True if no threats were found
        /// </summary>
        /// <value>True if no threats were found</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Contains executable content
        /// </summary>
        /// <value>Contains executable content</value>
        [DataMember(Name = "ContainsExecutable", EmitDefaultValue = true)]
        public bool ContainsExecutable { get; set; }

        /// <summary>
        /// Contains invalid file structure
        /// </summary>
        /// <value>Contains invalid file structure</value>
        [DataMember(Name = "ContainsInvalidFile", EmitDefaultValue = true)]
        public bool ContainsInvalidFile { get; set; }

        /// <summary>
        /// Contains script content
        /// </summary>
        /// <value>Contains script content</value>
        [DataMember(Name = "ContainsScript", EmitDefaultValue = true)]
        public bool ContainsScript { get; set; }

        /// <summary>
        /// File is password-protected
        /// </summary>
        /// <value>File is password-protected</value>
        [DataMember(Name = "ContainsPasswordProtectedFile", EmitDefaultValue = true)]
        public bool ContainsPasswordProtectedFile { get; set; }

        /// <summary>
        /// File format is restricted
        /// </summary>
        /// <value>File format is restricted</value>
        [DataMember(Name = "ContainsRestrictedFileFormat", EmitDefaultValue = true)]
        public bool ContainsRestrictedFileFormat { get; set; }

        /// <summary>
        /// Contains macro code
        /// </summary>
        /// <value>Contains macro code</value>
        [DataMember(Name = "ContainsMacros", EmitDefaultValue = true)]
        public bool ContainsMacros { get; set; }

        /// <summary>
        /// Contains XML external entities
        /// </summary>
        /// <value>Contains XML external entities</value>
        [DataMember(Name = "ContainsXmlExternalEntities", EmitDefaultValue = true)]
        public bool ContainsXmlExternalEntities { get; set; }

        /// <summary>
        /// Contains insecure deserialization
        /// </summary>
        /// <value>Contains insecure deserialization</value>
        [DataMember(Name = "ContainsInsecureDeserialization", EmitDefaultValue = true)]
        public bool ContainsInsecureDeserialization { get; set; }

        /// <summary>
        /// Contains HTML content
        /// </summary>
        /// <value>Contains HTML content</value>
        [DataMember(Name = "ContainsHtml", EmitDefaultValue = true)]
        public bool ContainsHtml { get; set; }

        /// <summary>
        /// Contains unsafe archive structure
        /// </summary>
        /// <value>Contains unsafe archive structure</value>
        [DataMember(Name = "ContainsUnsafeArchive", EmitDefaultValue = true)]
        public bool ContainsUnsafeArchive { get; set; }

        /// <summary>
        /// Contains OLE embedded objects
        /// </summary>
        /// <value>Contains OLE embedded objects</value>
        [DataMember(Name = "ContainsOleEmbeddedObject", EmitDefaultValue = true)]
        public bool ContainsOleEmbeddedObject { get; set; }

        /// <summary>
        /// Contains unwanted actions
        /// </summary>
        /// <value>Contains unwanted actions</value>
        [DataMember(Name = "ContainsUnwantedAction", EmitDefaultValue = true)]
        public bool ContainsUnwantedAction { get; set; }

        /// <summary>
        /// Content-verified file format
        /// </summary>
        /// <value>Content-verified file format</value>
        [DataMember(Name = "VerifiedFileFormat", EmitDefaultValue = false)]
        public string VerifiedFileFormat { get; set; }

        /// <summary>
        /// List of viruses found
        /// </summary>
        /// <value>List of viruses found</value>
        [DataMember(Name = "FoundViruses", EmitDefaultValue = false)]
        public List<VirusFound> FoundViruses { get; set; }

        /// <summary>
        /// Gets or Sets ContentInformation
        /// </summary>
        [DataMember(Name = "ContentInformation", EmitDefaultValue = false)]
        public VirusScanContentInfo ContentInformation { get; set; }

        /// <summary>
        /// Error message if the scan failed
        /// </summary>
        /// <value>Error message if the scan failed</value>
        [DataMember(Name = "ErrorMessage", EmitDefaultValue = false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirusScanResult {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsExecutable: ").Append(ContainsExecutable).Append("\n");
            sb.Append("  ContainsInvalidFile: ").Append(ContainsInvalidFile).Append("\n");
            sb.Append("  ContainsScript: ").Append(ContainsScript).Append("\n");
            sb.Append("  ContainsPasswordProtectedFile: ").Append(ContainsPasswordProtectedFile).Append("\n");
            sb.Append("  ContainsRestrictedFileFormat: ").Append(ContainsRestrictedFileFormat).Append("\n");
            sb.Append("  ContainsMacros: ").Append(ContainsMacros).Append("\n");
            sb.Append("  ContainsXmlExternalEntities: ").Append(ContainsXmlExternalEntities).Append("\n");
            sb.Append("  ContainsInsecureDeserialization: ").Append(ContainsInsecureDeserialization).Append("\n");
            sb.Append("  ContainsHtml: ").Append(ContainsHtml).Append("\n");
            sb.Append("  ContainsUnsafeArchive: ").Append(ContainsUnsafeArchive).Append("\n");
            sb.Append("  ContainsOleEmbeddedObject: ").Append(ContainsOleEmbeddedObject).Append("\n");
            sb.Append("  ContainsUnwantedAction: ").Append(ContainsUnwantedAction).Append("\n");
            sb.Append("  VerifiedFileFormat: ").Append(VerifiedFileFormat).Append("\n");
            sb.Append("  FoundViruses: ").Append(FoundViruses).Append("\n");
            sb.Append("  ContentInformation: ").Append(ContentInformation).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
