/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Model
{
    /// <summary>
    /// Additional content information from virus scan
    /// </summary>
    [DataContract(Name = "VirusScanContentInfo")]
    public partial class VirusScanContentInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirusScanContentInfo" /> class.
        /// </summary>
        /// <param name="containsJSON">File contains JSON content.</param>
        /// <param name="containsXML">File contains XML content.</param>
        /// <param name="containsImage">File contains image content.</param>
        /// <param name="hashSHA1">SHA-1 hash of the file.</param>
        /// <param name="relevantSubfileName">Name of relevant subfile.</param>
        /// <param name="relevantSubfileHashSHA1">SHA-1 hash of relevant subfile.</param>
        /// <param name="isAuthenticodeSigned">File has Authenticode signature.</param>
        public VirusScanContentInfo(bool containsJSON = default(bool), bool containsXML = default(bool), bool containsImage = default(bool), string hashSHA1 = default(string), string relevantSubfileName = default(string), string relevantSubfileHashSHA1 = default(string), bool isAuthenticodeSigned = default(bool))
        {
            this.ContainsJSON = containsJSON;
            this.ContainsXML = containsXML;
            this.ContainsImage = containsImage;
            this.HashSHA1 = hashSHA1;
            this.RelevantSubfileName = relevantSubfileName;
            this.RelevantSubfileHashSHA1 = relevantSubfileHashSHA1;
            this.IsAuthenticodeSigned = isAuthenticodeSigned;
        }

        /// <summary>
        /// File contains JSON content
        /// </summary>
        /// <value>File contains JSON content</value>
        [DataMember(Name = "ContainsJSON", EmitDefaultValue = true)]
        public bool ContainsJSON { get; set; }

        /// <summary>
        /// File contains XML content
        /// </summary>
        /// <value>File contains XML content</value>
        [DataMember(Name = "ContainsXML", EmitDefaultValue = true)]
        public bool ContainsXML { get; set; }

        /// <summary>
        /// File contains image content
        /// </summary>
        /// <value>File contains image content</value>
        [DataMember(Name = "ContainsImage", EmitDefaultValue = true)]
        public bool ContainsImage { get; set; }

        /// <summary>
        /// SHA-1 hash of the file
        /// </summary>
        /// <value>SHA-1 hash of the file</value>
        [DataMember(Name = "Hash_SHA1", EmitDefaultValue = false)]
        public string HashSHA1 { get; set; }

        /// <summary>
        /// Name of relevant subfile
        /// </summary>
        /// <value>Name of relevant subfile</value>
        [DataMember(Name = "RelevantSubfileName", EmitDefaultValue = false)]
        public string RelevantSubfileName { get; set; }

        /// <summary>
        /// SHA-1 hash of relevant subfile
        /// </summary>
        /// <value>SHA-1 hash of relevant subfile</value>
        [DataMember(Name = "RelevantSubfileHash_SHA1", EmitDefaultValue = false)]
        public string RelevantSubfileHashSHA1 { get; set; }

        /// <summary>
        /// File has Authenticode signature
        /// </summary>
        /// <value>File has Authenticode signature</value>
        [DataMember(Name = "IsAuthenticodeSigned", EmitDefaultValue = true)]
        public bool IsAuthenticodeSigned { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirusScanContentInfo {\n");
            sb.Append("  ContainsJSON: ").Append(ContainsJSON).Append("\n");
            sb.Append("  ContainsXML: ").Append(ContainsXML).Append("\n");
            sb.Append("  ContainsImage: ").Append(ContainsImage).Append("\n");
            sb.Append("  HashSHA1: ").Append(HashSHA1).Append("\n");
            sb.Append("  RelevantSubfileName: ").Append(RelevantSubfileName).Append("\n");
            sb.Append("  RelevantSubfileHashSHA1: ").Append(RelevantSubfileHashSHA1).Append("\n");
            sb.Append("  IsAuthenticodeSigned: ").Append(IsAuthenticodeSigned).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
