/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing AiContentDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AiContentDetectionResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AiContentDetectionResult
        //private AiContentDetectionResult instance;

        public AiContentDetectionResultTests()
        {
            // TODO uncomment below to create an instance of AiContentDetectionResult
            //instance = new AiContentDetectionResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AiContentDetectionResult
        /// </summary>
        [Fact]
        public void AiContentDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AiContentDetectionResult
            //Assert.IsType<AiContentDetectionResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsAiGeneratedContent'
        /// </summary>
        [Fact]
        public void ContainsAiGeneratedContentTest()
        {
            // TODO unit test for the property 'ContainsAiGeneratedContent'
        }

        /// <summary>
        /// Test the property 'AiConfidenceLevel'
        /// </summary>
        [Fact]
        public void AiConfidenceLevelTest()
        {
            // TODO unit test for the property 'AiConfidenceLevel'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'SkipReason'
        /// </summary>
        [Fact]
        public void SkipReasonTest()
        {
            // TODO unit test for the property 'SkipReason'
        }

        /// <summary>
        /// Test the property 'Verdict'
        /// </summary>
        [Fact]
        public void VerdictTest()
        {
            // TODO unit test for the property 'Verdict'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'Generator'
        /// </summary>
        [Fact]
        public void GeneratorTest()
        {
            // TODO unit test for the property 'Generator'
        }

        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Fact]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }

        /// <summary>
        /// Test the property 'DetectedFileType'
        /// </summary>
        [Fact]
        public void DetectedFileTypeTest()
        {
            // TODO unit test for the property 'DetectedFileType'
        }
    }
}
