/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing ContentScanningResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentScanningResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentScanningResult
        //private ContentScanningResult instance;

        public ContentScanningResultTests()
        {
            // TODO uncomment below to create an instance of ContentScanningResult
            //instance = new ContentScanningResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentScanningResult
        /// </summary>
        [Fact]
        public void ContentScanningResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentScanningResult
            //Assert.IsType<ContentScanningResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'DownloadedFileFormat'
        /// </summary>
        [Fact]
        public void DownloadedFileFormatTest()
        {
            // TODO unit test for the property 'DownloadedFileFormat'
        }

        /// <summary>
        /// Test the property 'NsfwDetection'
        /// </summary>
        [Fact]
        public void NsfwDetectionTest()
        {
            // TODO unit test for the property 'NsfwDetection'
        }

        /// <summary>
        /// Test the property 'AiContentDetection'
        /// </summary>
        [Fact]
        public void AiContentDetectionTest()
        {
            // TODO unit test for the property 'AiContentDetection'
        }

        /// <summary>
        /// Test the property 'FraudDetection'
        /// </summary>
        [Fact]
        public void FraudDetectionTest()
        {
            // TODO unit test for the property 'FraudDetection'
        }

        /// <summary>
        /// Test the property 'SpamDetection'
        /// </summary>
        [Fact]
        public void SpamDetectionTest()
        {
            // TODO unit test for the property 'SpamDetection'
        }

        /// <summary>
        /// Test the property 'DlpDetection'
        /// </summary>
        [Fact]
        public void DlpDetectionTest()
        {
            // TODO unit test for the property 'DlpDetection'
        }

        /// <summary>
        /// Test the property 'PolicyEnforcement'
        /// </summary>
        [Fact]
        public void PolicyEnforcementTest()
        {
            // TODO unit test for the property 'PolicyEnforcement'
        }
    }
}
