/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing DlpDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DlpDetectionResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DlpDetectionResult
        //private DlpDetectionResult instance;

        public DlpDetectionResultTests()
        {
            // TODO uncomment below to create an instance of DlpDetectionResult
            //instance = new DlpDetectionResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DlpDetectionResult
        /// </summary>
        [Fact]
        public void DlpDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" DlpDetectionResult
            //Assert.IsType<DlpDetectionResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsEmailAddresses'
        /// </summary>
        [Fact]
        public void ContainsEmailAddressesTest()
        {
            // TODO unit test for the property 'ContainsEmailAddresses'
        }

        /// <summary>
        /// Test the property 'ContainsPhoneNumbers'
        /// </summary>
        [Fact]
        public void ContainsPhoneNumbersTest()
        {
            // TODO unit test for the property 'ContainsPhoneNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsStreetAddresses'
        /// </summary>
        [Fact]
        public void ContainsStreetAddressesTest()
        {
            // TODO unit test for the property 'ContainsStreetAddresses'
        }

        /// <summary>
        /// Test the property 'ContainsPersonNames'
        /// </summary>
        [Fact]
        public void ContainsPersonNamesTest()
        {
            // TODO unit test for the property 'ContainsPersonNames'
        }

        /// <summary>
        /// Test the property 'ContainsBirthDates'
        /// </summary>
        [Fact]
        public void ContainsBirthDatesTest()
        {
            // TODO unit test for the property 'ContainsBirthDates'
        }

        /// <summary>
        /// Test the property 'ContainsPassportNumbers'
        /// </summary>
        [Fact]
        public void ContainsPassportNumbersTest()
        {
            // TODO unit test for the property 'ContainsPassportNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsDriversLicenses'
        /// </summary>
        [Fact]
        public void ContainsDriversLicensesTest()
        {
            // TODO unit test for the property 'ContainsDriversLicenses'
        }

        /// <summary>
        /// Test the property 'ContainsSocialSecurityNumbers'
        /// </summary>
        [Fact]
        public void ContainsSocialSecurityNumbersTest()
        {
            // TODO unit test for the property 'ContainsSocialSecurityNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsTaxpayerIds'
        /// </summary>
        [Fact]
        public void ContainsTaxpayerIdsTest()
        {
            // TODO unit test for the property 'ContainsTaxpayerIds'
        }

        /// <summary>
        /// Test the property 'ContainsCreditCardNumbers'
        /// </summary>
        [Fact]
        public void ContainsCreditCardNumbersTest()
        {
            // TODO unit test for the property 'ContainsCreditCardNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsBankAccountNumbers'
        /// </summary>
        [Fact]
        public void ContainsBankAccountNumbersTest()
        {
            // TODO unit test for the property 'ContainsBankAccountNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsIbans'
        /// </summary>
        [Fact]
        public void ContainsIbansTest()
        {
            // TODO unit test for the property 'ContainsIbans'
        }

        /// <summary>
        /// Test the property 'ContainsHealthInsuranceNumbers'
        /// </summary>
        [Fact]
        public void ContainsHealthInsuranceNumbersTest()
        {
            // TODO unit test for the property 'ContainsHealthInsuranceNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsBearerTokens'
        /// </summary>
        [Fact]
        public void ContainsBearerTokensTest()
        {
            // TODO unit test for the property 'ContainsBearerTokens'
        }

        /// <summary>
        /// Test the property 'ContainsHttpCookies'
        /// </summary>
        [Fact]
        public void ContainsHttpCookiesTest()
        {
            // TODO unit test for the property 'ContainsHttpCookies'
        }

        /// <summary>
        /// Test the property 'ContainsPrivateKeys'
        /// </summary>
        [Fact]
        public void ContainsPrivateKeysTest()
        {
            // TODO unit test for the property 'ContainsPrivateKeys'
        }

        /// <summary>
        /// Test the property 'ContainsCredentials'
        /// </summary>
        [Fact]
        public void ContainsCredentialsTest()
        {
            // TODO unit test for the property 'ContainsCredentials'
        }

        /// <summary>
        /// Test the property 'ContainsDeepWebUrls'
        /// </summary>
        [Fact]
        public void ContainsDeepWebUrlsTest()
        {
            // TODO unit test for the property 'ContainsDeepWebUrls'
        }

        /// <summary>
        /// Test the property 'ContainsSourceCode'
        /// </summary>
        [Fact]
        public void ContainsSourceCodeTest()
        {
            // TODO unit test for the property 'ContainsSourceCode'
        }

        /// <summary>
        /// Test the property 'ContainsIpAddresses'
        /// </summary>
        [Fact]
        public void ContainsIpAddressesTest()
        {
            // TODO unit test for the property 'ContainsIpAddresses'
        }

        /// <summary>
        /// Test the property 'ContainsMacAddresses'
        /// </summary>
        [Fact]
        public void ContainsMacAddressesTest()
        {
            // TODO unit test for the property 'ContainsMacAddresses'
        }

        /// <summary>
        /// Test the property 'ContainsHealthInsuranceMemberIds'
        /// </summary>
        [Fact]
        public void ContainsHealthInsuranceMemberIdsTest()
        {
            // TODO unit test for the property 'ContainsHealthInsuranceMemberIds'
        }

        /// <summary>
        /// Test the property 'ContainsInjuryDiseaseReferences'
        /// </summary>
        [Fact]
        public void ContainsInjuryDiseaseReferencesTest()
        {
            // TODO unit test for the property 'ContainsInjuryDiseaseReferences'
        }

        /// <summary>
        /// Test the property 'ContainsTreatmentTypeDescriptions'
        /// </summary>
        [Fact]
        public void ContainsTreatmentTypeDescriptionsTest()
        {
            // TODO unit test for the property 'ContainsTreatmentTypeDescriptions'
        }

        /// <summary>
        /// Test the property 'ContainsMedicalTreatmentDates'
        /// </summary>
        [Fact]
        public void ContainsMedicalTreatmentDatesTest()
        {
            // TODO unit test for the property 'ContainsMedicalTreatmentDates'
        }

        /// <summary>
        /// Test the property 'ContainsHealthPlanBeneficiaryNumbers'
        /// </summary>
        [Fact]
        public void ContainsHealthPlanBeneficiaryNumbersTest()
        {
            // TODO unit test for the property 'ContainsHealthPlanBeneficiaryNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsTreatmentPayments'
        /// </summary>
        [Fact]
        public void ContainsTreatmentPaymentsTest()
        {
            // TODO unit test for the property 'ContainsTreatmentPayments'
        }

        /// <summary>
        /// Test the property 'ContainsVehicleIds'
        /// </summary>
        [Fact]
        public void ContainsVehicleIdsTest()
        {
            // TODO unit test for the property 'ContainsVehicleIds'
        }

        /// <summary>
        /// Test the property 'ContainsDeviceIds'
        /// </summary>
        [Fact]
        public void ContainsDeviceIdsTest()
        {
            // TODO unit test for the property 'ContainsDeviceIds'
        }

        /// <summary>
        /// Test the property 'AnalysisRationale'
        /// </summary>
        [Fact]
        public void AnalysisRationaleTest()
        {
            // TODO unit test for the property 'AnalysisRationale'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'SkipReason'
        /// </summary>
        [Fact]
        public void SkipReasonTest()
        {
            // TODO unit test for the property 'SkipReason'
        }
    }
}
