/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing DlpDetectionFileConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DlpDetectionFileConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DlpDetectionFileConfig
        //private DlpDetectionFileConfig instance;

        public DlpDetectionFileConfigTests()
        {
            // TODO uncomment below to create an instance of DlpDetectionFileConfig
            //instance = new DlpDetectionFileConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DlpDetectionFileConfig
        /// </summary>
        [Fact]
        public void DlpDetectionFileConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" DlpDetectionFileConfig
            //Assert.IsType<DlpDetectionFileConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'AllowEmailAddresses'
        /// </summary>
        [Fact]
        public void AllowEmailAddressesTest()
        {
            // TODO unit test for the property 'AllowEmailAddresses'
        }

        /// <summary>
        /// Test the property 'AllowPhoneNumbers'
        /// </summary>
        [Fact]
        public void AllowPhoneNumbersTest()
        {
            // TODO unit test for the property 'AllowPhoneNumbers'
        }

        /// <summary>
        /// Test the property 'AllowStreetAddresses'
        /// </summary>
        [Fact]
        public void AllowStreetAddressesTest()
        {
            // TODO unit test for the property 'AllowStreetAddresses'
        }

        /// <summary>
        /// Test the property 'AllowPersonNames'
        /// </summary>
        [Fact]
        public void AllowPersonNamesTest()
        {
            // TODO unit test for the property 'AllowPersonNames'
        }

        /// <summary>
        /// Test the property 'AllowBirthDates'
        /// </summary>
        [Fact]
        public void AllowBirthDatesTest()
        {
            // TODO unit test for the property 'AllowBirthDates'
        }

        /// <summary>
        /// Test the property 'AllowPassportNumbers'
        /// </summary>
        [Fact]
        public void AllowPassportNumbersTest()
        {
            // TODO unit test for the property 'AllowPassportNumbers'
        }

        /// <summary>
        /// Test the property 'AllowDriversLicenses'
        /// </summary>
        [Fact]
        public void AllowDriversLicensesTest()
        {
            // TODO unit test for the property 'AllowDriversLicenses'
        }

        /// <summary>
        /// Test the property 'AllowSocialSecurityNumbers'
        /// </summary>
        [Fact]
        public void AllowSocialSecurityNumbersTest()
        {
            // TODO unit test for the property 'AllowSocialSecurityNumbers'
        }

        /// <summary>
        /// Test the property 'AllowTaxpayerIds'
        /// </summary>
        [Fact]
        public void AllowTaxpayerIdsTest()
        {
            // TODO unit test for the property 'AllowTaxpayerIds'
        }

        /// <summary>
        /// Test the property 'AllowCreditCardNumbers'
        /// </summary>
        [Fact]
        public void AllowCreditCardNumbersTest()
        {
            // TODO unit test for the property 'AllowCreditCardNumbers'
        }

        /// <summary>
        /// Test the property 'AllowBankAccountNumbers'
        /// </summary>
        [Fact]
        public void AllowBankAccountNumbersTest()
        {
            // TODO unit test for the property 'AllowBankAccountNumbers'
        }

        /// <summary>
        /// Test the property 'AllowIbans'
        /// </summary>
        [Fact]
        public void AllowIbansTest()
        {
            // TODO unit test for the property 'AllowIbans'
        }

        /// <summary>
        /// Test the property 'AllowHealthInsuranceNumbers'
        /// </summary>
        [Fact]
        public void AllowHealthInsuranceNumbersTest()
        {
            // TODO unit test for the property 'AllowHealthInsuranceNumbers'
        }

        /// <summary>
        /// Test the property 'AllowBearerTokens'
        /// </summary>
        [Fact]
        public void AllowBearerTokensTest()
        {
            // TODO unit test for the property 'AllowBearerTokens'
        }

        /// <summary>
        /// Test the property 'AllowHttpCookies'
        /// </summary>
        [Fact]
        public void AllowHttpCookiesTest()
        {
            // TODO unit test for the property 'AllowHttpCookies'
        }

        /// <summary>
        /// Test the property 'AllowPrivateKeys'
        /// </summary>
        [Fact]
        public void AllowPrivateKeysTest()
        {
            // TODO unit test for the property 'AllowPrivateKeys'
        }

        /// <summary>
        /// Test the property 'AllowCredentials'
        /// </summary>
        [Fact]
        public void AllowCredentialsTest()
        {
            // TODO unit test for the property 'AllowCredentials'
        }

        /// <summary>
        /// Test the property 'AllowDeepWebUrls'
        /// </summary>
        [Fact]
        public void AllowDeepWebUrlsTest()
        {
            // TODO unit test for the property 'AllowDeepWebUrls'
        }

        /// <summary>
        /// Test the property 'AllowSourceCode'
        /// </summary>
        [Fact]
        public void AllowSourceCodeTest()
        {
            // TODO unit test for the property 'AllowSourceCode'
        }

        /// <summary>
        /// Test the property 'AllowIpAddresses'
        /// </summary>
        [Fact]
        public void AllowIpAddressesTest()
        {
            // TODO unit test for the property 'AllowIpAddresses'
        }

        /// <summary>
        /// Test the property 'AllowMacAddresses'
        /// </summary>
        [Fact]
        public void AllowMacAddressesTest()
        {
            // TODO unit test for the property 'AllowMacAddresses'
        }

        /// <summary>
        /// Test the property 'AllowHealthInsuranceMemberIds'
        /// </summary>
        [Fact]
        public void AllowHealthInsuranceMemberIdsTest()
        {
            // TODO unit test for the property 'AllowHealthInsuranceMemberIds'
        }

        /// <summary>
        /// Test the property 'AllowInjuryDiseaseReferences'
        /// </summary>
        [Fact]
        public void AllowInjuryDiseaseReferencesTest()
        {
            // TODO unit test for the property 'AllowInjuryDiseaseReferences'
        }

        /// <summary>
        /// Test the property 'AllowTreatmentTypeDescriptions'
        /// </summary>
        [Fact]
        public void AllowTreatmentTypeDescriptionsTest()
        {
            // TODO unit test for the property 'AllowTreatmentTypeDescriptions'
        }

        /// <summary>
        /// Test the property 'AllowMedicalTreatmentDates'
        /// </summary>
        [Fact]
        public void AllowMedicalTreatmentDatesTest()
        {
            // TODO unit test for the property 'AllowMedicalTreatmentDates'
        }

        /// <summary>
        /// Test the property 'AllowHealthPlanBeneficiaryNumbers'
        /// </summary>
        [Fact]
        public void AllowHealthPlanBeneficiaryNumbersTest()
        {
            // TODO unit test for the property 'AllowHealthPlanBeneficiaryNumbers'
        }

        /// <summary>
        /// Test the property 'AllowTreatmentPayments'
        /// </summary>
        [Fact]
        public void AllowTreatmentPaymentsTest()
        {
            // TODO unit test for the property 'AllowTreatmentPayments'
        }

        /// <summary>
        /// Test the property 'AllowVehicleIds'
        /// </summary>
        [Fact]
        public void AllowVehicleIdsTest()
        {
            // TODO unit test for the property 'AllowVehicleIds'
        }

        /// <summary>
        /// Test the property 'AllowDeviceIds'
        /// </summary>
        [Fact]
        public void AllowDeviceIdsTest()
        {
            // TODO unit test for the property 'AllowDeviceIds'
        }

        /// <summary>
        /// Test the property 'ProvideAnalysisRationale'
        /// </summary>
        [Fact]
        public void ProvideAnalysisRationaleTest()
        {
            // TODO unit test for the property 'ProvideAnalysisRationale'
        }

        /// <summary>
        /// Test the property 'CustomPolicyID'
        /// </summary>
        [Fact]
        public void CustomPolicyIDTest()
        {
            // TODO unit test for the property 'CustomPolicyID'
        }

        /// <summary>
        /// Test the property 'RecognitionMode'
        /// </summary>
        [Fact]
        public void RecognitionModeTest()
        {
            // TODO unit test for the property 'RecognitionMode'
        }
    }
}
