/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing FraudDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FraudDetectionResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FraudDetectionResult
        //private FraudDetectionResult instance;

        public FraudDetectionResultTests()
        {
            // TODO uncomment below to create an instance of FraudDetectionResult
            //instance = new FraudDetectionResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FraudDetectionResult
        /// </summary>
        [Fact]
        public void FraudDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" FraudDetectionResult
            //Assert.IsType<FraudDetectionResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'FraudRiskLevel'
        /// </summary>
        [Fact]
        public void FraudRiskLevelTest()
        {
            // TODO unit test for the property 'FraudRiskLevel'
        }

        /// <summary>
        /// Test the property 'ContainsFinancialLiability'
        /// </summary>
        [Fact]
        public void ContainsFinancialLiabilityTest()
        {
            // TODO unit test for the property 'ContainsFinancialLiability'
        }

        /// <summary>
        /// Test the property 'ContainsSensitiveInformationCollection'
        /// </summary>
        [Fact]
        public void ContainsSensitiveInformationCollectionTest()
        {
            // TODO unit test for the property 'ContainsSensitiveInformationCollection'
        }

        /// <summary>
        /// Test the property 'ContainsAssetTransfer'
        /// </summary>
        [Fact]
        public void ContainsAssetTransferTest()
        {
            // TODO unit test for the property 'ContainsAssetTransfer'
        }

        /// <summary>
        /// Test the property 'ContainsPurchaseAgreement'
        /// </summary>
        [Fact]
        public void ContainsPurchaseAgreementTest()
        {
            // TODO unit test for the property 'ContainsPurchaseAgreement'
        }

        /// <summary>
        /// Test the property 'ContainsEmploymentAgreement'
        /// </summary>
        [Fact]
        public void ContainsEmploymentAgreementTest()
        {
            // TODO unit test for the property 'ContainsEmploymentAgreement'
        }

        /// <summary>
        /// Test the property 'ContainsExpiredDocument'
        /// </summary>
        [Fact]
        public void ContainsExpiredDocumentTest()
        {
            // TODO unit test for the property 'ContainsExpiredDocument'
        }

        /// <summary>
        /// Test the property 'ContainsAiGeneratedContent'
        /// </summary>
        [Fact]
        public void ContainsAiGeneratedContentTest()
        {
            // TODO unit test for the property 'ContainsAiGeneratedContent'
        }

        /// <summary>
        /// Test the property 'AnalysisRationale'
        /// </summary>
        [Fact]
        public void AnalysisRationaleTest()
        {
            // TODO unit test for the property 'AnalysisRationale'
        }

        /// <summary>
        /// Test the property 'DocumentClass'
        /// </summary>
        [Fact]
        public void DocumentClassTest()
        {
            // TODO unit test for the property 'DocumentClass'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'SkipReason'
        /// </summary>
        [Fact]
        public void SkipReasonTest()
        {
            // TODO unit test for the property 'SkipReason'
        }
    }
}
