/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing FraudDetectionConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FraudDetectionConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FraudDetectionConfig
        //private FraudDetectionConfig instance;

        public FraudDetectionConfigTests()
        {
            // TODO uncomment below to create an instance of FraudDetectionConfig
            //instance = new FraudDetectionConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FraudDetectionConfig
        /// </summary>
        [Fact]
        public void FraudDetectionConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" FraudDetectionConfig
            //Assert.IsType<FraudDetectionConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Preprocessing'
        /// </summary>
        [Fact]
        public void PreprocessingTest()
        {
            // TODO unit test for the property 'Preprocessing'
        }

        /// <summary>
        /// Test the property 'ResultCrossCheck'
        /// </summary>
        [Fact]
        public void ResultCrossCheckTest()
        {
            // TODO unit test for the property 'ResultCrossCheck'
        }

        /// <summary>
        /// Test the property 'UserEmailAddress'
        /// </summary>
        [Fact]
        public void UserEmailAddressTest()
        {
            // TODO unit test for the property 'UserEmailAddress'
        }

        /// <summary>
        /// Test the property 'UserEmailAddressVerified'
        /// </summary>
        [Fact]
        public void UserEmailAddressVerifiedTest()
        {
            // TODO unit test for the property 'UserEmailAddressVerified'
        }
    }
}
