/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing MultiThreatFileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiThreatFileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MultiThreatFileResponse
        //private MultiThreatFileResponse instance;

        public MultiThreatFileResponseTests()
        {
            // TODO uncomment below to create an instance of MultiThreatFileResponse
            //instance = new MultiThreatFileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiThreatFileResponse
        /// </summary>
        [Fact]
        public void MultiThreatFileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MultiThreatFileResponse
            //Assert.IsType<MultiThreatFileResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'VerifiedFileFormat'
        /// </summary>
        [Fact]
        public void VerifiedFileFormatTest()
        {
            // TODO unit test for the property 'VerifiedFileFormat'
        }

        /// <summary>
        /// Test the property 'ScanResults'
        /// </summary>
        [Fact]
        public void ScanResultsTest()
        {
            // TODO unit test for the property 'ScanResults'
        }
    }
}
