/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing NsfwDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NsfwDetectionResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NsfwDetectionResult
        //private NsfwDetectionResult instance;

        public NsfwDetectionResultTests()
        {
            // TODO uncomment below to create an instance of NsfwDetectionResult
            //instance = new NsfwDetectionResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NsfwDetectionResult
        /// </summary>
        [Fact]
        public void NsfwDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" NsfwDetectionResult
            //Assert.IsType<NsfwDetectionResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsNudity'
        /// </summary>
        [Fact]
        public void ContainsNudityTest()
        {
            // TODO unit test for the property 'ContainsNudity'
        }

        /// <summary>
        /// Test the property 'ContainsGraphicViolence'
        /// </summary>
        [Fact]
        public void ContainsGraphicViolenceTest()
        {
            // TODO unit test for the property 'ContainsGraphicViolence'
        }

        /// <summary>
        /// Test the property 'ContainsNonGraphicViolence'
        /// </summary>
        [Fact]
        public void ContainsNonGraphicViolenceTest()
        {
            // TODO unit test for the property 'ContainsNonGraphicViolence'
        }

        /// <summary>
        /// Test the property 'ContainsSelfHarm'
        /// </summary>
        [Fact]
        public void ContainsSelfHarmTest()
        {
            // TODO unit test for the property 'ContainsSelfHarm'
        }

        /// <summary>
        /// Test the property 'ContainsHate'
        /// </summary>
        [Fact]
        public void ContainsHateTest()
        {
            // TODO unit test for the property 'ContainsHate'
        }

        /// <summary>
        /// Test the property 'ContainsPotentialIllegalActivity'
        /// </summary>
        [Fact]
        public void ContainsPotentialIllegalActivityTest()
        {
            // TODO unit test for the property 'ContainsPotentialIllegalActivity'
        }

        /// <summary>
        /// Test the property 'ContainsMedicalImagery'
        /// </summary>
        [Fact]
        public void ContainsMedicalImageryTest()
        {
            // TODO unit test for the property 'ContainsMedicalImagery'
        }

        /// <summary>
        /// Test the property 'ContainsProfanity'
        /// </summary>
        [Fact]
        public void ContainsProfanityTest()
        {
            // TODO unit test for the property 'ContainsProfanity'
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

        /// <summary>
        /// Test the property 'ClassificationOutcome'
        /// </summary>
        [Fact]
        public void ClassificationOutcomeTest()
        {
            // TODO unit test for the property 'ClassificationOutcome'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'SkipReason'
        /// </summary>
        [Fact]
        public void SkipReasonTest()
        {
            // TODO unit test for the property 'SkipReason'
        }
    }
}
