/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing PhishingDetectionTextResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhishingDetectionTextResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhishingDetectionTextResult
        //private PhishingDetectionTextResult instance;

        public PhishingDetectionTextResultTests()
        {
            // TODO uncomment below to create an instance of PhishingDetectionTextResult
            //instance = new PhishingDetectionTextResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionTextResult
        /// </summary>
        [Fact]
        public void PhishingDetectionTextResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhishingDetectionTextResult
            //Assert.IsType<PhishingDetectionTextResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsPhishing'
        /// </summary>
        [Fact]
        public void ContainsPhishingTest()
        {
            // TODO unit test for the property 'ContainsPhishing'
        }

        /// <summary>
        /// Test the property 'ContainsUnsolicitedSales'
        /// </summary>
        [Fact]
        public void ContainsUnsolicitedSalesTest()
        {
            // TODO unit test for the property 'ContainsUnsolicitedSales'
        }

        /// <summary>
        /// Test the property 'ContainsPromotionalContent'
        /// </summary>
        [Fact]
        public void ContainsPromotionalContentTest()
        {
            // TODO unit test for the property 'ContainsPromotionalContent'
        }

        /// <summary>
        /// Test the property 'ContainsWebUrls'
        /// </summary>
        [Fact]
        public void ContainsWebUrlsTest()
        {
            // TODO unit test for the property 'ContainsWebUrls'
        }

        /// <summary>
        /// Test the property 'ContainsPhoneNumbers'
        /// </summary>
        [Fact]
        public void ContainsPhoneNumbersTest()
        {
            // TODO unit test for the property 'ContainsPhoneNumbers'
        }

        /// <summary>
        /// Test the property 'ContainsEmailAddresses'
        /// </summary>
        [Fact]
        public void ContainsEmailAddressesTest()
        {
            // TODO unit test for the property 'ContainsEmailAddresses'
        }

        /// <summary>
        /// Test the property 'ConfidenceLevel'
        /// </summary>
        [Fact]
        public void ConfidenceLevelTest()
        {
            // TODO unit test for the property 'ConfidenceLevel'
        }

        /// <summary>
        /// Test the property 'AnalysisRationale'
        /// </summary>
        [Fact]
        public void AnalysisRationaleTest()
        {
            // TODO unit test for the property 'AnalysisRationale'
        }

        /// <summary>
        /// Test the property 'UnsafeUrls'
        /// </summary>
        [Fact]
        public void UnsafeUrlsTest()
        {
            // TODO unit test for the property 'UnsafeUrls'
        }
    }
}
