/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing PhishingDetectionFileResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhishingDetectionFileResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhishingDetectionFileResult
        //private PhishingDetectionFileResult instance;

        public PhishingDetectionFileResultTests()
        {
            // TODO uncomment below to create an instance of PhishingDetectionFileResult
            //instance = new PhishingDetectionFileResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionFileResult
        /// </summary>
        [Fact]
        public void PhishingDetectionFileResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhishingDetectionFileResult
            //Assert.IsType<PhishingDetectionFileResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsPhishing'
        /// </summary>
        [Fact]
        public void ContainsPhishingTest()
        {
            // TODO unit test for the property 'ContainsPhishing'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'SkipReason'
        /// </summary>
        [Fact]
        public void SkipReasonTest()
        {
            // TODO unit test for the property 'SkipReason'
        }
    }
}
