/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing PolicyEnforcementResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PolicyEnforcementResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PolicyEnforcementResult
        //private PolicyEnforcementResult instance;

        public PolicyEnforcementResultTests()
        {
            // TODO uncomment below to create an instance of PolicyEnforcementResult
            //instance = new PolicyEnforcementResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PolicyEnforcementResult
        /// </summary>
        [Fact]
        public void PolicyEnforcementResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" PolicyEnforcementResult
            //Assert.IsType<PolicyEnforcementResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'RiskScore'
        /// </summary>
        [Fact]
        public void RiskScoreTest()
        {
            // TODO unit test for the property 'RiskScore'
        }

        /// <summary>
        /// Test the property 'RuleViolations'
        /// </summary>
        [Fact]
        public void RuleViolationsTest()
        {
            // TODO unit test for the property 'RuleViolations'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'SkipReason'
        /// </summary>
        [Fact]
        public void SkipReasonTest()
        {
            // TODO unit test for the property 'SkipReason'
        }
    }
}
