/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing PolicyRuleViolation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PolicyRuleViolationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PolicyRuleViolation
        //private PolicyRuleViolation instance;

        public PolicyRuleViolationTests()
        {
            // TODO uncomment below to create an instance of PolicyRuleViolation
            //instance = new PolicyRuleViolation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PolicyRuleViolation
        /// </summary>
        [Fact]
        public void PolicyRuleViolationInstanceTest()
        {
            // TODO uncomment below to test "IsType" PolicyRuleViolation
            //Assert.IsType<PolicyRuleViolation>(instance);
        }

        /// <summary>
        /// Test the property 'RuleId'
        /// </summary>
        [Fact]
        public void RuleIdTest()
        {
            // TODO unit test for the property 'RuleId'
        }

        /// <summary>
        /// Test the property 'RuleViolationRiskScore'
        /// </summary>
        [Fact]
        public void RuleViolationRiskScoreTest()
        {
            // TODO unit test for the property 'RuleViolationRiskScore'
        }

        /// <summary>
        /// Test the property 'RuleViolationRationale'
        /// </summary>
        [Fact]
        public void RuleViolationRationaleTest()
        {
            // TODO unit test for the property 'RuleViolationRationale'
        }
    }
}
