/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing PolicyRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PolicyRuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PolicyRule
        //private PolicyRule instance;

        public PolicyRuleTests()
        {
            // TODO uncomment below to create an instance of PolicyRule
            //instance = new PolicyRule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PolicyRule
        /// </summary>
        [Fact]
        public void PolicyRuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" PolicyRule
            //Assert.IsType<PolicyRule>(instance);
        }

        /// <summary>
        /// Test the property 'RuleId'
        /// </summary>
        [Fact]
        public void RuleIdTest()
        {
            // TODO unit test for the property 'RuleId'
        }

        /// <summary>
        /// Test the property 'RuleType'
        /// </summary>
        [Fact]
        public void RuleTypeTest()
        {
            // TODO unit test for the property 'RuleType'
        }

        /// <summary>
        /// Test the property 'RuleDescription'
        /// </summary>
        [Fact]
        public void RuleDescriptionTest()
        {
            // TODO unit test for the property 'RuleDescription'
        }
    }
}
