/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionResult
        //private SpamDetectionResult instance;

        public SpamDetectionResultTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionResult
            //instance = new SpamDetectionResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionResult
        /// </summary>
        [Fact]
        public void SpamDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionResult
            //Assert.IsType<SpamDetectionResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'SpamRiskLevel'
        /// </summary>
        [Fact]
        public void SpamRiskLevelTest()
        {
            // TODO unit test for the property 'SpamRiskLevel'
        }

        /// <summary>
        /// Test the property 'ContainsSpam'
        /// </summary>
        [Fact]
        public void ContainsSpamTest()
        {
            // TODO unit test for the property 'ContainsSpam'
        }

        /// <summary>
        /// Test the property 'ContainsUnsolicitedSales'
        /// </summary>
        [Fact]
        public void ContainsUnsolicitedSalesTest()
        {
            // TODO unit test for the property 'ContainsUnsolicitedSales'
        }

        /// <summary>
        /// Test the property 'ContainsPromotionalContent'
        /// </summary>
        [Fact]
        public void ContainsPromotionalContentTest()
        {
            // TODO unit test for the property 'ContainsPromotionalContent'
        }

        /// <summary>
        /// Test the property 'ContainsPhishingAttempt'
        /// </summary>
        [Fact]
        public void ContainsPhishingAttemptTest()
        {
            // TODO unit test for the property 'ContainsPhishingAttempt'
        }

        /// <summary>
        /// Test the property 'AnalysisRationale'
        /// </summary>
        [Fact]
        public void AnalysisRationaleTest()
        {
            // TODO unit test for the property 'AnalysisRationale'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'SkipReason'
        /// </summary>
        [Fact]
        public void SkipReasonTest()
        {
            // TODO unit test for the property 'SkipReason'
        }
    }
}
