/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionConfig
        //private SpamDetectionConfig instance;

        public SpamDetectionConfigTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionConfig
            //instance = new SpamDetectionConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionConfig
        /// </summary>
        [Fact]
        public void SpamDetectionConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionConfig
            //Assert.IsType<SpamDetectionConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'AllowUnsolicitedSales'
        /// </summary>
        [Fact]
        public void AllowUnsolicitedSalesTest()
        {
            // TODO unit test for the property 'AllowUnsolicitedSales'
        }

        /// <summary>
        /// Test the property 'AllowPromotionalContent'
        /// </summary>
        [Fact]
        public void AllowPromotionalContentTest()
        {
            // TODO unit test for the property 'AllowPromotionalContent'
        }

        /// <summary>
        /// Test the property 'AllowPhishing'
        /// </summary>
        [Fact]
        public void AllowPhishingTest()
        {
            // TODO unit test for the property 'AllowPhishing'
        }
    }
}
