/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing TextScanResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TextScanResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TextScanResults
        //private TextScanResults instance;

        public TextScanResultsTests()
        {
            // TODO uncomment below to create an instance of TextScanResults
            //instance = new TextScanResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TextScanResults
        /// </summary>
        [Fact]
        public void TextScanResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TextScanResults
            //Assert.IsType<TextScanResults>(instance);
        }

        /// <summary>
        /// Test the property 'VirusScan'
        /// </summary>
        [Fact]
        public void VirusScanTest()
        {
            // TODO unit test for the property 'VirusScan'
        }

        /// <summary>
        /// Test the property 'PhishingDetection'
        /// </summary>
        [Fact]
        public void PhishingDetectionTest()
        {
            // TODO unit test for the property 'PhishingDetection'
        }

        /// <summary>
        /// Test the property 'SpamDetection'
        /// </summary>
        [Fact]
        public void SpamDetectionTest()
        {
            // TODO unit test for the property 'SpamDetection'
        }

        /// <summary>
        /// Test the property 'DlpDetection'
        /// </summary>
        [Fact]
        public void DlpDetectionTest()
        {
            // TODO unit test for the property 'DlpDetection'
        }

        /// <summary>
        /// Test the property 'PolicyEnforcement'
        /// </summary>
        [Fact]
        public void PolicyEnforcementTest()
        {
            // TODO unit test for the property 'PolicyEnforcement'
        }
    }
}
