/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing UnsafeUrlInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnsafeUrlInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnsafeUrlInfo
        //private UnsafeUrlInfo instance;

        public UnsafeUrlInfoTests()
        {
            // TODO uncomment below to create an instance of UnsafeUrlInfo
            //instance = new UnsafeUrlInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnsafeUrlInfo
        /// </summary>
        [Fact]
        public void UnsafeUrlInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnsafeUrlInfo
            //Assert.IsType<UnsafeUrlInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'IsSsrfThreat'
        /// </summary>
        [Fact]
        public void IsSsrfThreatTest()
        {
            // TODO unit test for the property 'IsSsrfThreat'
        }

        /// <summary>
        /// Test the property 'ContainsPhishing'
        /// </summary>
        [Fact]
        public void ContainsPhishingTest()
        {
            // TODO unit test for the property 'ContainsPhishing'
        }
    }
}
