/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing UrlVirusScanConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UrlVirusScanConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UrlVirusScanConfig
        //private UrlVirusScanConfig instance;

        public UrlVirusScanConfigTests()
        {
            // TODO uncomment below to create an instance of UrlVirusScanConfig
            //instance = new UrlVirusScanConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UrlVirusScanConfig
        /// </summary>
        [Fact]
        public void UrlVirusScanConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" UrlVirusScanConfig
            //Assert.IsType<UrlVirusScanConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
    }
}
