/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing VirusScanContentInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirusScanContentInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirusScanContentInfo
        //private VirusScanContentInfo instance;

        public VirusScanContentInfoTests()
        {
            // TODO uncomment below to create an instance of VirusScanContentInfo
            //instance = new VirusScanContentInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirusScanContentInfo
        /// </summary>
        [Fact]
        public void VirusScanContentInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirusScanContentInfo
            //Assert.IsType<VirusScanContentInfo>(instance);
        }

        /// <summary>
        /// Test the property 'ContainsJSON'
        /// </summary>
        [Fact]
        public void ContainsJSONTest()
        {
            // TODO unit test for the property 'ContainsJSON'
        }

        /// <summary>
        /// Test the property 'ContainsXML'
        /// </summary>
        [Fact]
        public void ContainsXMLTest()
        {
            // TODO unit test for the property 'ContainsXML'
        }

        /// <summary>
        /// Test the property 'ContainsImage'
        /// </summary>
        [Fact]
        public void ContainsImageTest()
        {
            // TODO unit test for the property 'ContainsImage'
        }

        /// <summary>
        /// Test the property 'HashSHA1'
        /// </summary>
        [Fact]
        public void HashSHA1Test()
        {
            // TODO unit test for the property 'HashSHA1'
        }

        /// <summary>
        /// Test the property 'RelevantSubfileName'
        /// </summary>
        [Fact]
        public void RelevantSubfileNameTest()
        {
            // TODO unit test for the property 'RelevantSubfileName'
        }

        /// <summary>
        /// Test the property 'RelevantSubfileHashSHA1'
        /// </summary>
        [Fact]
        public void RelevantSubfileHashSHA1Test()
        {
            // TODO unit test for the property 'RelevantSubfileHashSHA1'
        }

        /// <summary>
        /// Test the property 'IsAuthenticodeSigned'
        /// </summary>
        [Fact]
        public void IsAuthenticodeSignedTest()
        {
            // TODO unit test for the property 'IsAuthenticodeSigned'
        }
    }
}
