/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing VirusScanConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirusScanConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirusScanConfig
        //private VirusScanConfig instance;

        public VirusScanConfigTests()
        {
            // TODO uncomment below to create an instance of VirusScanConfig
            //instance = new VirusScanConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirusScanConfig
        /// </summary>
        [Fact]
        public void VirusScanConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirusScanConfig
            //Assert.IsType<VirusScanConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'AllowExecutables'
        /// </summary>
        [Fact]
        public void AllowExecutablesTest()
        {
            // TODO unit test for the property 'AllowExecutables'
        }

        /// <summary>
        /// Test the property 'AllowInvalidFiles'
        /// </summary>
        [Fact]
        public void AllowInvalidFilesTest()
        {
            // TODO unit test for the property 'AllowInvalidFiles'
        }

        /// <summary>
        /// Test the property 'AllowScripts'
        /// </summary>
        [Fact]
        public void AllowScriptsTest()
        {
            // TODO unit test for the property 'AllowScripts'
        }

        /// <summary>
        /// Test the property 'AllowPasswordProtectedFiles'
        /// </summary>
        [Fact]
        public void AllowPasswordProtectedFilesTest()
        {
            // TODO unit test for the property 'AllowPasswordProtectedFiles'
        }

        /// <summary>
        /// Test the property 'AllowMacros'
        /// </summary>
        [Fact]
        public void AllowMacrosTest()
        {
            // TODO unit test for the property 'AllowMacros'
        }

        /// <summary>
        /// Test the property 'AllowXmlExternalEntities'
        /// </summary>
        [Fact]
        public void AllowXmlExternalEntitiesTest()
        {
            // TODO unit test for the property 'AllowXmlExternalEntities'
        }

        /// <summary>
        /// Test the property 'AllowInsecureDeserialization'
        /// </summary>
        [Fact]
        public void AllowInsecureDeserializationTest()
        {
            // TODO unit test for the property 'AllowInsecureDeserialization'
        }

        /// <summary>
        /// Test the property 'AllowHtml'
        /// </summary>
        [Fact]
        public void AllowHtmlTest()
        {
            // TODO unit test for the property 'AllowHtml'
        }

        /// <summary>
        /// Test the property 'AllowUnsafeArchives'
        /// </summary>
        [Fact]
        public void AllowUnsafeArchivesTest()
        {
            // TODO unit test for the property 'AllowUnsafeArchives'
        }

        /// <summary>
        /// Test the property 'AllowOleEmbeddedObject'
        /// </summary>
        [Fact]
        public void AllowOleEmbeddedObjectTest()
        {
            // TODO unit test for the property 'AllowOleEmbeddedObject'
        }

        /// <summary>
        /// Test the property 'AllowUnwantedAction'
        /// </summary>
        [Fact]
        public void AllowUnwantedActionTest()
        {
            // TODO unit test for the property 'AllowUnwantedAction'
        }

        /// <summary>
        /// Test the property 'RestrictFileTypes'
        /// </summary>
        [Fact]
        public void RestrictFileTypesTest()
        {
            // TODO unit test for the property 'RestrictFileTypes'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
    }
}
