/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing VirusScanUrlResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirusScanUrlResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirusScanUrlResult
        //private VirusScanUrlResult instance;

        public VirusScanUrlResultTests()
        {
            // TODO uncomment below to create an instance of VirusScanUrlResult
            //instance = new VirusScanUrlResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirusScanUrlResult
        /// </summary>
        [Fact]
        public void VirusScanUrlResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirusScanUrlResult
            //Assert.IsType<VirusScanUrlResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'WebsiteThreatType'
        /// </summary>
        [Fact]
        public void WebsiteThreatTypeTest()
        {
            // TODO unit test for the property 'WebsiteThreatType'
        }

        /// <summary>
        /// Test the property 'FoundViruses'
        /// </summary>
        [Fact]
        public void FoundVirusesTest()
        {
            // TODO unit test for the property 'FoundViruses'
        }

        /// <summary>
        /// Test the property 'WebsiteHttpResponseCode'
        /// </summary>
        [Fact]
        public void WebsiteHttpResponseCodeTest()
        {
            // TODO unit test for the property 'WebsiteHttpResponseCode'
        }
    }
}
