/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Model
{
    /// <summary>
    ///  Class for testing VirusScanResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VirusScanResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VirusScanResult
        //private VirusScanResult instance;

        public VirusScanResultTests()
        {
            // TODO uncomment below to create an instance of VirusScanResult
            //instance = new VirusScanResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VirusScanResult
        /// </summary>
        [Fact]
        public void VirusScanResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" VirusScanResult
            //Assert.IsType<VirusScanResult>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsExecutable'
        /// </summary>
        [Fact]
        public void ContainsExecutableTest()
        {
            // TODO unit test for the property 'ContainsExecutable'
        }

        /// <summary>
        /// Test the property 'ContainsInvalidFile'
        /// </summary>
        [Fact]
        public void ContainsInvalidFileTest()
        {
            // TODO unit test for the property 'ContainsInvalidFile'
        }

        /// <summary>
        /// Test the property 'ContainsScript'
        /// </summary>
        [Fact]
        public void ContainsScriptTest()
        {
            // TODO unit test for the property 'ContainsScript'
        }

        /// <summary>
        /// Test the property 'ContainsPasswordProtectedFile'
        /// </summary>
        [Fact]
        public void ContainsPasswordProtectedFileTest()
        {
            // TODO unit test for the property 'ContainsPasswordProtectedFile'
        }

        /// <summary>
        /// Test the property 'ContainsRestrictedFileFormat'
        /// </summary>
        [Fact]
        public void ContainsRestrictedFileFormatTest()
        {
            // TODO unit test for the property 'ContainsRestrictedFileFormat'
        }

        /// <summary>
        /// Test the property 'ContainsMacros'
        /// </summary>
        [Fact]
        public void ContainsMacrosTest()
        {
            // TODO unit test for the property 'ContainsMacros'
        }

        /// <summary>
        /// Test the property 'ContainsXmlExternalEntities'
        /// </summary>
        [Fact]
        public void ContainsXmlExternalEntitiesTest()
        {
            // TODO unit test for the property 'ContainsXmlExternalEntities'
        }

        /// <summary>
        /// Test the property 'ContainsInsecureDeserialization'
        /// </summary>
        [Fact]
        public void ContainsInsecureDeserializationTest()
        {
            // TODO unit test for the property 'ContainsInsecureDeserialization'
        }

        /// <summary>
        /// Test the property 'ContainsHtml'
        /// </summary>
        [Fact]
        public void ContainsHtmlTest()
        {
            // TODO unit test for the property 'ContainsHtml'
        }

        /// <summary>
        /// Test the property 'ContainsUnsafeArchive'
        /// </summary>
        [Fact]
        public void ContainsUnsafeArchiveTest()
        {
            // TODO unit test for the property 'ContainsUnsafeArchive'
        }

        /// <summary>
        /// Test the property 'ContainsOleEmbeddedObject'
        /// </summary>
        [Fact]
        public void ContainsOleEmbeddedObjectTest()
        {
            // TODO unit test for the property 'ContainsOleEmbeddedObject'
        }

        /// <summary>
        /// Test the property 'ContainsUnwantedAction'
        /// </summary>
        [Fact]
        public void ContainsUnwantedActionTest()
        {
            // TODO unit test for the property 'ContainsUnwantedAction'
        }

        /// <summary>
        /// Test the property 'VerifiedFileFormat'
        /// </summary>
        [Fact]
        public void VerifiedFileFormatTest()
        {
            // TODO unit test for the property 'VerifiedFileFormat'
        }

        /// <summary>
        /// Test the property 'FoundViruses'
        /// </summary>
        [Fact]
        public void FoundVirusesTest()
        {
            // TODO unit test for the property 'FoundViruses'
        }

        /// <summary>
        /// Test the property 'ContentInformation'
        /// </summary>
        [Fact]
        public void ContentInformationTest()
        {
            // TODO unit test for the property 'ContentInformation'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
    }
}
