/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Test.Api
{
    /// <summary>
    ///  Class for testing MultiThreatApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MultiThreatApiTests : IDisposable
    {
        private MultiThreatApi instance;

        public MultiThreatApiTests()
        {
            instance = new MultiThreatApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiThreatApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MultiThreatApi
            //Assert.IsType<MultiThreatApi>(instance);
        }

        /// <summary>
        /// Test MultiThreatScanFilePost
        /// </summary>
        [Fact]
        public void MultiThreatScanFilePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //string config = null;
            //var response = instance.MultiThreatScanFilePost(inputFile, config);
            //Assert.IsType<MultiThreatFileResponse>(response);
        }

        /// <summary>
        /// Test MultiThreatScanTextPost
        /// </summary>
        [Fact]
        public void MultiThreatScanTextPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MultiThreatTextRequest body = null;
            //var response = instance.MultiThreatScanTextPost(body);
            //Assert.IsType<MultiThreatTextResponse>(response);
        }

        /// <summary>
        /// Test MultiThreatScanUrlPost
        /// </summary>
        [Fact]
        public void MultiThreatScanUrlPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MultiThreatUrlRequest body = null;
            //var response = instance.MultiThreatScanUrlPost(body);
            //Assert.IsType<MultiThreatUrlResponse>(response);
        }
    }
}
