/*
 * multithreatscanapi
 *
 * Scan text, files, and URLs for multiple threat types in a single API call.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Client;
using Cloudmersive.APIClient.NETCore.MultiThreatScan.Model;

namespace Cloudmersive.APIClient.NETCore.MultiThreatScan.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMultiThreatApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>MultiThreatFileResponse</returns>
        MultiThreatFileResponse MultiThreatScanFilePost(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0);

        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of MultiThreatFileResponse</returns>
        ApiResponse<MultiThreatFileResponse> MultiThreatScanFilePostWithHttpInfo(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0);
        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>MultiThreatTextResponse</returns>
        MultiThreatTextResponse MultiThreatScanTextPost(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0);

        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of MultiThreatTextResponse</returns>
        ApiResponse<MultiThreatTextResponse> MultiThreatScanTextPostWithHttpInfo(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0);
        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>MultiThreatUrlResponse</returns>
        MultiThreatUrlResponse MultiThreatScanUrlPost(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0);

        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of MultiThreatUrlResponse</returns>
        ApiResponse<MultiThreatUrlResponse> MultiThreatScanUrlPostWithHttpInfo(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMultiThreatApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MultiThreatFileResponse</returns>
        System.Threading.Tasks.Task<MultiThreatFileResponse> MultiThreatScanFilePostAsync(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MultiThreatFileResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MultiThreatFileResponse>> MultiThreatScanFilePostWithHttpInfoAsync(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MultiThreatTextResponse</returns>
        System.Threading.Tasks.Task<MultiThreatTextResponse> MultiThreatScanTextPostAsync(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MultiThreatTextResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MultiThreatTextResponse>> MultiThreatScanTextPostWithHttpInfoAsync(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MultiThreatUrlResponse</returns>
        System.Threading.Tasks.Task<MultiThreatUrlResponse> MultiThreatScanUrlPostAsync(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MultiThreatUrlResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MultiThreatUrlResponse>> MultiThreatScanUrlPostWithHttpInfoAsync(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMultiThreatApi : IMultiThreatApiSync, IMultiThreatApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MultiThreatApi : IMultiThreatApi
    {
        private Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiThreatApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MultiThreatApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiThreatApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MultiThreatApi(string basePath)
        {
            this.Configuration = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiThreatApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MultiThreatApi(Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiThreatApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MultiThreatApi(Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ISynchronousClient client, Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.IAsynchronousClient asyncClient, Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>MultiThreatFileResponse</returns>
        public MultiThreatFileResponse MultiThreatScanFilePost(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatFileResponse> localVarResponse = MultiThreatScanFilePostWithHttpInfo(inputFile, config);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of MultiThreatFileResponse</returns>
        public Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatFileResponse> MultiThreatScanFilePostWithHttpInfo(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0)
        {
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
            {
                throw new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException(400, "Missing required parameter 'inputFile' when calling MultiThreatApi->MultiThreatScanFilePost");
            }

            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.FileParameters.Add("inputFile", inputFile);
            if (config != null)
            {
                localVarRequestOptions.FormParameters.Add("config", Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.ParameterToString(config)); // form parameter
            }

            localVarRequestOptions.Operation = "MultiThreatApi.MultiThreatScanFilePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<MultiThreatFileResponse>("/multi-threat-scan/file", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MultiThreatScanFilePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MultiThreatFileResponse</returns>
        public async System.Threading.Tasks.Task<MultiThreatFileResponse> MultiThreatScanFilePostAsync(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatFileResponse> localVarResponse = await MultiThreatScanFilePostWithHttpInfoAsync(inputFile, config, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Scan a file for multiple threat types including viruses, NSFW, AI-generated content, fraud, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">The file to scan</param>
        /// <param name="config">Optional JSON scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MultiThreatFileResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatFileResponse>> MultiThreatScanFilePostWithHttpInfoAsync(System.IO.Stream inputFile, string config = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
            {
                throw new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException(400, "Missing required parameter 'inputFile' when calling MultiThreatApi->MultiThreatScanFilePost");
            }


            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.FileParameters.Add("inputFile", inputFile);
            if (config != null)
            {
                localVarRequestOptions.FormParameters.Add("config", Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.ParameterToString(config)); // form parameter
            }

            localVarRequestOptions.Operation = "MultiThreatApi.MultiThreatScanFilePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<MultiThreatFileResponse>("/multi-threat-scan/file", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MultiThreatScanFilePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>MultiThreatTextResponse</returns>
        public MultiThreatTextResponse MultiThreatScanTextPost(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatTextResponse> localVarResponse = MultiThreatScanTextPostWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of MultiThreatTextResponse</returns>
        public Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatTextResponse> MultiThreatScanTextPostWithHttpInfo(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "MultiThreatApi.MultiThreatScanTextPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<MultiThreatTextResponse>("/multi-threat-scan/text", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MultiThreatScanTextPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MultiThreatTextResponse</returns>
        public async System.Threading.Tasks.Task<MultiThreatTextResponse> MultiThreatScanTextPostAsync(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatTextResponse> localVarResponse = await MultiThreatScanTextPostWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Scan text for multiple threat types including viruses, phishing, spam, DLP, and policy violations in a single API call. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Text scan request with content and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MultiThreatTextResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatTextResponse>> MultiThreatScanTextPostWithHttpInfoAsync(MultiThreatTextRequest body = default(MultiThreatTextRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "MultiThreatApi.MultiThreatScanTextPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<MultiThreatTextResponse>("/multi-threat-scan/text", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MultiThreatScanTextPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>MultiThreatUrlResponse</returns>
        public MultiThreatUrlResponse MultiThreatScanUrlPost(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatUrlResponse> localVarResponse = MultiThreatScanUrlPostWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of MultiThreatUrlResponse</returns>
        public Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatUrlResponse> MultiThreatScanUrlPostWithHttpInfo(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0)
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "MultiThreatApi.MultiThreatScanUrlPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<MultiThreatUrlResponse>("/multi-threat-scan/url", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MultiThreatScanUrlPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MultiThreatUrlResponse</returns>
        public async System.Threading.Tasks.Task<MultiThreatUrlResponse> MultiThreatScanUrlPostAsync(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatUrlResponse> localVarResponse = await MultiThreatScanUrlPostWithHttpInfoAsync(body, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Scan a URL for multiple threat types including viruses, phishing, and policy violations in a single API call. Optionally download and scan the file at the URL. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL scan request with URL and scan configuration (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MultiThreatUrlResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ApiResponse<MultiThreatUrlResponse>> MultiThreatScanUrlPostWithHttpInfoAsync(MultiThreatUrlRequest body = default(MultiThreatUrlRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Cloudmersive.APIClient.NETCore.MultiThreatScan.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = body;

            localVarRequestOptions.Operation = "MultiThreatApi.MultiThreatScanUrlPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<MultiThreatUrlResponse>("/multi-threat-scan/url", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MultiThreatScanUrlPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
